import { defineEntity } from './define';
import { medFeature, medPoint } from '../mediterraneanMap';
import type { EntityBookSet } from './index';

// Places & People cards for the Mecca Before Islam books (A2, B1, B2), English and Arabic.
// Generated from the reviewed card list; the chapters are where each level's story
// names the place. Sources are TDV İslâm Ansiklopedisi article titles.

const CITY_ZOOM = 1.8;

const entities = [
  defineEntity({
    id: "mecca-mecca-7th-century", kind: "city", tr: "Mekke",
    aliases: { en: ["Mecca"], ar: ["مكة"] },
    copy: {
      en: { title: "Mecca", kindLabel: "City", periodLabel: "Before Islam · Arabia", summary: "Mecca is a city in a dry valley in the west of the Arabian Peninsula. The Ka’ba is here, and before Islam it was a busy trade city.", more: "Today, millions of Muslims visit Mecca every year for Hajj." },
      ar: { title: "مَكَّةُ", kindLabel: "مَدِينَةٌ", periodLabel: "قَبْلَ الْإِسْلَامِ · شِبْهُ الْجَزِيرَةِ الْعَرَبِيَّةِ", summary: "مَكَّةُ مَدِينَةٌ فِي وَادٍ جَافٍّ غَرْبَ شِبْهِ الْجَزِيرَةِ الْعَرَبِيَّةِ. فِيهَا الْكَعْبَةُ الْمُشَرَّفَةُ، وَكَانَتْ قَبْلَ الْإِسْلَامِ مَدِينَةً تِجَارِيَّةً نَشِيطَةً.", more: "يَزُورُ مَكَّةَ الْيَوْمَ مَلَايِينُ الْمُسْلِمِينَ كُلَّ عَامٍ لِأَدَاءِ الْحَجِّ." },
    },
    focus: medPoint(21.42, 39.83, CITY_ZOOM),
    picture: { folder: "mecca", name: "mecca-7th-century" },
    sources: ["TDV İslâm Ansiklopedisi: Mekke"],
  }),
  defineEntity({
    id: "mecca-mecca-valley-ancient", kind: "landmark", tr: "Mekke",
    aliases: { en: ["a valley where no crops grow"], ar: ["واد غير ذي زرع"] },
    copy: {
      en: { title: "Valley of Mecca", kindLabel: "Valley", periodLabel: "Time of Abraham (pbuh)", summary: "In the time of Abraham (pbuh), Mecca was an empty, dry valley where no crops grew. No people lived there before Zamzam water was found.", more: "Bare, rocky mountains stand all around the valley." },
      ar: { title: "وَادِي مَكَّةَ", kindLabel: "وَادٍ", periodLabel: "زَمَنُ إِبْرَاهِيمَ عَلَيْهِ السَّلَامُ", summary: "فِي زَمَنِ إِبْرَاهِيمَ عَلَيْهِ السَّلَامُ، كَانَتْ مَكَّةُ وَادِيًا جَافًّا خَالِيًا لَا زَرْعَ فِيهِ. وَلَمْ يَكُنْ فِيهِ سُكَّانٌ قَبْلَ اكْتِشَافِ مَاءِ زَمْزَمَ.", more: "تُحِيطُ بِالْوَادِي جِبَالٌ صَخْرِيَّةٌ جَرْدَاءُ مِنْ كُلِّ جِهَةٍ." },
    },
    focus: medPoint(21.42, 39.83, CITY_ZOOM),
    picture: { folder: "mecca", name: "mecca-valley-ancient" },
    sources: ["TDV İslâm Ansiklopedisi: Mekke"],
  }),
  defineEntity({
    id: "mecca-medina-7th-century", kind: "city", tr: "Medine",
    aliases: { en: ["Medina"], ar: ["الهجرة إلى المدينة","هجرته إلى المدينة"] },
    copy: {
      en: { title: "Medina", kindLabel: "City", periodLabel: "7th century · Arabia", summary: "Medina is a city north of Mecca, in the west of the Arabian Peninsula. After many hard years in Mecca, the Prophet (pbuh) and the Muslims moved here; this move is called the Hijrah.", more: "Before Islam, the city was called Yathrib." },
      ar: { title: "الْمَدِينَةُ", kindLabel: "مَدِينَةٌ", periodLabel: "الْقَرْنُ السَّابِعُ · شِبْهُ الْجَزِيرَةِ الْعَرَبِيَّةِ", summary: "الْمَدِينَةُ بَلْدَةٌ تَقَعُ شَمَالَ مَكَّةَ، فِي غَرْبِ شِبْهِ الْجَزِيرَةِ الْعَرَبِيَّةِ. هَاجَرَ إِلَيْهَا الرَّسُولُ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ وَالْمُسْلِمُونَ بَعْدَ سَنَوَاتٍ صَعْبَةٍ فِي مَكَّةَ، وَتُسَمَّى هَذِهِ الرِّحْلَةُ الْهِجْرَةَ.", more: "كَانَ اسْمُهَا قَبْلَ الْإِسْلَامِ يَثْرِبَ." },
    },
    focus: medPoint(24.47, 39.61, CITY_ZOOM),
    picture: { folder: "mecca", name: "medina-7th-century" },
    sources: ["TDV İslâm Ansiklopedisi: Medine"],
  }),
  defineEntity({
    id: "mecca-damascus-7th-century", kind: "city", tr: "Şam",
    aliases: { en: ["Damascus"], ar: ["دمشق"] },
    copy: {
      en: { title: "Damascus", kindLabel: "City", periodLabel: "7th century · Syria", summary: "Damascus is an old city in Syria, north of Arabia. After the Prophet (pbuh) died, Bilal left Medina, went to Damascus and died there.", more: "Today, it is the capital of Syria." },
      ar: { title: "دِمَشْقُ", kindLabel: "مَدِينَةٌ", periodLabel: "الْقَرْنُ السَّابِعُ · الشَّامُ", summary: "دِمَشْقُ مَدِينَةٌ قَدِيمَةٌ فِي بِلَادِ الشَّامِ، شَمَالَ شِبْهِ الْجَزِيرَةِ الْعَرَبِيَّةِ. وَبَعْدَ وَفَاةِ الرَّسُولِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ، خَرَجَ بِلَالٌ مِنَ الْمَدِينَةِ إِلَى دِمَشْقَ وَمَاتَ فِيهَا.", more: "وَهِيَ الْيَوْمَ عَاصِمَةُ سُورِيَا." },
    },
    focus: medPoint(33.51, 36.28, CITY_ZOOM),
    picture: { folder: "mecca", name: "damascus-7th-century" },
    sources: ["TDV İslâm Ansiklopedisi: Dımaşk"],
  }),
  defineEntity({
    id: "mecca-constantinople-byzantine", kind: "city", tr: "Kostantiniyye",
    aliases: { en: ["Constantinople","Istanbul"], ar: ["القسطنطينية","إسطنبول"] },
    copy: {
      en: { title: "Constantinople", kindLabel: "City", periodLabel: "Byzantine Empire", summary: "Constantinople was the capital city of the Byzantine Empire. Today we call it Istanbul.", more: "It stands on the Bosphorus, where Europe meets Asia." },
      ar: { title: "الْقُسْطَنْطِينِيَّةُ", kindLabel: "مَدِينَةٌ", periodLabel: "الْإِمْبِرَاطُورِيَّةُ الْبِيزَنْطِيَّةُ", summary: "كَانَتِ الْقُسْطَنْطِينِيَّةُ عَاصِمَةَ الْإِمْبِرَاطُورِيَّةِ الْبِيزَنْطِيَّةِ. وَنُسَمِّيهَا الْيَوْمَ إِسْطَنْبُولَ.", more: "تَقَعُ عَلَى مَضِيقِ الْبُوسْفُورِ، حَيْثُ تَلْتَقِي أُورُوبَّا بِآسِيَا." },
    },
    focus: medPoint(41.01, 28.98, CITY_ZOOM),
    picture: { folder: "mecca", name: "constantinople-byzantine" },
    sources: ["TDV İslâm Ansiklopedisi: İstanbul"],
  }),
  defineEntity({
    id: "mecca-arabian-peninsula", kind: "region", tr: "Arap Yarımadası",
    aliases: { en: ["Arabian Peninsula","Arabia"], ar: ["شبه الجزيرة العربية","شبه جزيرة العرب","بلاد العرب"] },
    copy: {
      en: { title: "Arabian Peninsula", kindLabel: "Peninsula", periodLabel: "Before Islam", summary: "The Arabian Peninsula is a large, dry land with water on three sides. Before Islam, it had no single government, and people lived in tribes.", more: "Most of it is desert, and it gets very little rain." },
      ar: { title: "شِبْهُ الْجَزِيرَةِ الْعَرَبِيَّةِ", kindLabel: "شِبْهُ جَزِيرَةٍ", periodLabel: "قَبْلَ الْإِسْلَامِ", summary: "شِبْهُ الْجَزِيرَةِ الْعَرَبِيَّةِ أَرْضٌ وَاسِعَةٌ جَافَّةٌ، يُحِيطُ بِهَا الْمَاءُ مِنْ ثَلَاثِ جِهَاتٍ. وَلَمْ تَكُنْ فِيهَا قَبْلَ الْإِسْلَامِ حُكُومَةٌ وَاحِدَةٌ، بَلْ كَانَ النَّاسُ يَعِيشُونَ فِي قَبَائِلَ.", more: "أَكْثَرُهَا صَحْرَاءُ، وَالْمَطَرُ فِيهَا قَلِيلٌ جِدًّا." },
    },
    focus: medFeature('arabian-peninsula', 23, 45, 1),
    picture: { folder: "mecca", name: "arabian-peninsula" },
    sources: ["TDV İslâm Ansiklopedisi: Arabistan"],
  }),
  defineEntity({
    id: "mecca-abyssinia", kind: "country", tr: "Habeşistan",
    aliases: { en: ["Abyssinia","Ethiopia"], ar: ["الحبشة","حبشي","إثيوبيا"] },
    copy: {
      en: { title: "Abyssinia (Ethiopia)", kindLabel: "Land", periodLabel: "East Africa", summary: "Abyssinia is the old name of Ethiopia, a land in East Africa, across the Red Sea from Arabia. Bilal’s mother was from Abyssinia, and Meccan merchants traded with it.", more: "A great old kingdom there was called Aksum." },
      ar: { title: "الْحَبَشَةُ", kindLabel: "بِلَادٌ", periodLabel: "شَرْقُ إِفْرِيقِيَا", summary: "الْحَبَشَةُ اسْمٌ قَدِيمٌ لِإِثْيُوبِيَا، وَهِيَ بِلَادٌ فِي شَرْقِ إِفْرِيقِيَا تُقَابِلُ بِلَادَ الْعَرَبِ عَبْرَ الْبَحْرِ الْأَحْمَرِ. كَانَتْ أُمُّ بِلَالٍ حَبَشِيَّةً، وَكَانَ تُجَّارُ مَكَّةَ يُتَاجِرُونَ مَعَهَا.", more: "كَانَتْ فِيهَا مَمْلَكَةٌ قَدِيمَةٌ عَظِيمَةٌ اسْمُهَا أَكْسُومُ." },
    },
    focus: medFeature('abyssinia', 12.5, 39, 1, { view: { north: 32, west: 26, widthDegrees: 30 } }),
    picture: { folder: "mecca", name: "abyssinia" },
    sources: ["TDV İslâm Ansiklopedisi: Habeşistan"],
  }),
  defineEntity({
    id: "mecca-yemen-6th-century", kind: "country",
    aliases: { en: ["Yemen"], ar: ["اليمن"] },
    copy: {
      en: { title: "Yemen", kindLabel: "Land", periodLabel: "South Arabia", summary: "Yemen is a land in the south-west of the Arabian Peninsula. Goods from the East came to its coast, and caravans carried them to the north.", more: "Its green mountains get more rain than the rest of Arabia." },
      ar: { title: "الْيَمَنُ", kindLabel: "بِلَادٌ", periodLabel: "جَنُوبُ شِبْهِ الْجَزِيرَةِ الْعَرَبِيَّةِ", summary: "الْيَمَنُ بِلَادٌ فِي جَنُوبِ غَرْبِ شِبْهِ الْجَزِيرَةِ الْعَرَبِيَّةِ. كَانَتْ بَضَائِعُ الشَّرْقِ تَصِلُ إِلَى سَوَاحِلِهِ، ثُمَّ تَحْمِلُهَا الْقَوَافِلُ إِلَى الشَّمَالِ.", more: "تَنْزِلُ عَلَى جِبَالِهِ الْخَضْرَاءِ أَمْطَارٌ أَكْثَرُ مِنْ بَقِيَّةِ بِلَادِ الْعَرَبِ." },
    },
    focus: medFeature('yemen', 15.5, 46.5, 1, { view: { north: 32, west: 30, widthDegrees: 30 } }),
    picture: { folder: "mecca", name: "yemen-6th-century" },
    sources: ["TDV İslâm Ansiklopedisi: Yemen"],
  }),
  defineEntity({
    id: "mecca-palestine-ancient", kind: "region", tr: "Filistin",
    aliases: { en: ["Palestine"], ar: ["فلسطين"] },
    copy: {
      en: { title: "Palestine", kindLabel: "Land", periodLabel: "Eastern Mediterranean", summary: "Palestine is a land by the Mediterranean Sea, north of Arabia. Abraham (pbuh) went back there after his visit to Mecca, and trade caravans also traveled there.", more: "The city of Jerusalem is in Palestine." },
      ar: { title: "فِلَسْطِينُ", kindLabel: "بِلَادٌ", periodLabel: "شَرْقُ الْبَحْرِ الْأَبْيَضِ الْمُتَوَسِّطِ", summary: "فِلَسْطِينُ بِلَادٌ عَلَى سَاحِلِ الْبَحْرِ الْأَبْيَضِ الْمُتَوَسِّطِ، شَمَالَ بِلَادِ الْعَرَبِ. عَادَ إِلَيْهَا إِبْرَاهِيمُ عَلَيْهِ السَّلَامُ بَعْدَ زِيَارَتِهِ لِمَكَّةَ، وَكَانَتِ الْقَوَافِلُ التِّجَارِيَّةُ تَذْهَبُ إِلَيْهَا أَيْضًا.", more: "مَدِينَةُ الْقُدْسِ فِي فِلَسْطِينَ." },
    },
    focus: medFeature('palestine', 31.6, 35, 1),
    picture: { folder: "mecca", name: "palestine-ancient" },
    sources: ["TDV İslâm Ansiklopedisi: Filistin"],
  }),
  defineEntity({
    id: "mecca-iraq-6th-century", kind: "region", tr: "Irak",
    aliases: { en: ["Iraq"], ar: ["العراق"] },
    copy: {
      en: { title: "Iraq", kindLabel: "Land", periodLabel: "6th century", summary: "Iraq is the land of two great rivers, the Tigris and the Euphrates, north-east of Arabia. Meccan merchants traveled there to trade.", more: "In those days, the Sassanid Persians ruled it." },
      ar: { title: "الْعِرَاقُ", kindLabel: "بِلَادٌ", periodLabel: "الْقَرْنُ السَّادِسُ", summary: "الْعِرَاقُ بِلَادُ النَّهْرَيْنِ الْعَظِيمَيْنِ دِجْلَةَ وَالْفُرَاتِ، شَمَالَ شَرْقِ بِلَادِ الْعَرَبِ. وَكَانَ تُجَّارُ مَكَّةَ يُسَافِرُونَ إِلَيْهِ لِلتِّجَارَةِ.", more: "كَانَ الْفُرْسُ السَّاسَانِيُّونَ يَحْكُمُونَهُ فِي ذَلِكَ الْوَقْتِ." },
    },
    focus: medFeature('iraq', 33, 44, 1),
    picture: { folder: "mecca", name: "iraq-6th-century" },
    sources: ["TDV İslâm Ansiklopedisi: Irak"],
  }),
  defineEntity({
    id: "mecca-syria-byzantine", kind: "region", tr: "Suriye",
    aliases: { en: ["Syria"], ar: ["الشام"] },
    copy: {
      en: { title: "Syria", kindLabel: "Land", periodLabel: "6th century", summary: "Syria is a land north of Arabia, by the Mediterranean Sea. Trade caravans from Arabia carried goods there.", more: "Damascus is one of its most famous cities." },
      ar: { title: "الشَّامُ", kindLabel: "بِلَادٌ", periodLabel: "الْقَرْنُ السَّادِسُ", summary: "الشَّامُ بِلَادٌ تَقَعُ شَمَالَ شِبْهِ الْجَزِيرَةِ الْعَرَبِيَّةِ، عَلَى سَاحِلِ الْبَحْرِ الْأَبْيَضِ الْمُتَوَسِّطِ. وَكَانَتِ الْقَوَافِلُ التِّجَارِيَّةُ تَحْمِلُ الْبَضَائِعَ إِلَيْهَا مِنْ بِلَادِ الْعَرَبِ.", more: "دِمَشْقُ مِنْ أَشْهَرِ مُدُنِهَا." },
    },
    focus: medFeature('syria', 34.5, 37.5, 1),
    picture: { folder: "mecca", name: "syria-byzantine" },
    sources: ["TDV İslâm Ansiklopedisi: Suriye"],
  }),
  defineEntity({
    id: "mecca-egypt-byzantine", kind: "country", tr: "Mısır",
    aliases: { en: ["Egypt"], ar: ["مصر"] },
    copy: {
      en: { title: "Egypt", kindLabel: "Land", periodLabel: "Byzantine Empire", summary: "Egypt is a land in North Africa, on the Nile River. It was the richest part of the Byzantine Empire, and Meccan caravans went there to trade.", more: "The great pyramids are in Egypt." },
      ar: { title: "مِصْرُ", kindLabel: "بِلَادٌ", periodLabel: "الْإِمْبِرَاطُورِيَّةُ الْبِيزَنْطِيَّةُ", summary: "مِصْرُ بِلَادٌ فِي شَمَالِ إِفْرِيقِيَا عَلَى نَهْرِ النِّيلِ. كَانَتْ أَغْنَى مَنَاطِقِ الْإِمْبِرَاطُورِيَّةِ الْبِيزَنْطِيَّةِ، وَكَانَتْ قَوَافِلُ قُرَيْشٍ تَذْهَبُ إِلَيْهَا لِلتِّجَارَةِ.", more: "تُوجَدُ الْأَهْرَامَاتُ الشَّهِيرَةُ فِي مِصْرَ." },
    },
    focus: medFeature('egypt', 27, 30.5, 1),
    picture: { folder: "mecca", name: "egypt-byzantine" },
    sources: ["TDV İslâm Ansiklopedisi: Mısır"],
  }),
  defineEntity({
    id: "mecca-india-ancient", kind: "country", tr: "Hindistan",
    aliases: { en: ["India"], ar: ["الهند"] },
    copy: {
      en: { title: "India", kindLabel: "Land", periodLabel: "South Asia", summary: "India is a large land far to the east of Arabia. It made many goods, and these goods came to Arabia for trade.", more: "Spices like pepper come from India." },
      ar: { title: "الْهِنْدُ", kindLabel: "بِلَادٌ", periodLabel: "جَنُوبُ آسِيَا", summary: "الْهِنْدُ بِلَادٌ وَاسِعَةٌ تَقَعُ بَعِيدًا شَرْقَ بِلَادِ الْعَرَبِ. كَانَتْ تُنْتِجُ بَضَائِعَ كَثِيرَةً، وَكَانَتْ هَذِهِ الْبَضَائِعُ تَصِلُ إِلَى بِلَادِ الْعَرَبِ لِلتِّجَارَةِ.", more: "تَأْتِي مِنَ الْهِنْدِ تَوَابِلُ مِثْلُ الْفُلْفُلِ." },
    },
    focus: medFeature('india', 22, 78, 1, { view: { north: 38, west: 40, widthDegrees: 60 } }),
    picture: { folder: "mecca", name: "india-ancient" },
    sources: ["TDV İslâm Ansiklopedisi: Hindistan"],
  }),
  defineEntity({
    id: "mecca-indonesia-ancient", kind: "island", tr: "Endonezya",
    aliases: { en: ["Indonesia"], ar: ["إندونيسيا"] },
    copy: {
      en: { title: "Indonesia", kindLabel: "Islands", periodLabel: "Southeast Asia", summary: "Indonesia is a land of many islands, far away in Southeast Asia. Its goods reached Arabia through trade.", more: "Spices like cloves and nutmeg grow there." },
      ar: { title: "إِنْدُونِيسِيَا", kindLabel: "جُزُرٌ", periodLabel: "جَنُوبُ شَرْقِ آسِيَا", summary: "إِنْدُونِيسِيَا بِلَادٌ مِنْ جُزُرٍ كَثِيرَةٍ، بَعِيدَةٌ فِي جَنُوبِ شَرْقِ آسِيَا. وَكَانَتْ بَضَائِعُهَا تَصِلُ إِلَى بِلَادِ الْعَرَبِ عَنْ طَرِيقِ التِّجَارَةِ.", more: "يَنْمُو فِيهَا الْقَرَنْفُلُ وَجَوْزَةُ الطِّيبِ." },
    },
    focus: medFeature('indonesia', -2, 113, 1, { view: { north: 25, west: 67, widthDegrees: 60 } }),
    picture: { folder: "mecca", name: "indonesia-ancient" },
    sources: ["TDV İslâm Ansiklopedisi: Endonezya"],
  }),
  defineEntity({
    id: "mecca-china-ancient", kind: "country", tr: "Çin",
    aliases: { en: ["China"], ar: ["الصين"] },
    copy: {
      en: { title: "China", kindLabel: "Land", periodLabel: "East Asia", summary: "China is a very large land far in the east of Asia. It made many goods, and these goods reached Arabia through trade.", more: "China was famous for its silk." },
      ar: { title: "الصِّينُ", kindLabel: "بِلَادٌ", periodLabel: "شَرْقُ آسِيَا", summary: "الصِّينُ بِلَادٌ وَاسِعَةٌ جِدًّا فِي أَقْصَى شَرْقِ آسِيَا. كَانَتْ تُنْتِجُ بَضَائِعَ كَثِيرَةً تَصِلُ إِلَى بِلَادِ الْعَرَبِ عَنْ طَرِيقِ التِّجَارَةِ.", more: "اشْتَهَرَتِ الصِّينُ بِالْحَرِيرِ." },
    },
    focus: medFeature('china', 33, 105, 1, { view: { north: 50, west: 67, widthDegrees: 60 } }),
    picture: { folder: "mecca", name: "china-ancient" },
    sources: ["TDV İslâm Ansiklopedisi: Çin"],
  }),
  defineEntity({
    id: "mecca-africa", kind: "region", tr: "Afrika",
    aliases: { en: ["Africa"], ar: ["إفريقيا"] },
    copy: {
      en: { title: "Africa", kindLabel: "Continent", periodLabel: "Across the Red Sea", summary: "Africa is a very large continent across the Red Sea from Arabia. Many slaves in Mecca were brought from Africa.", more: "Egypt and Abyssinia are both in Africa." },
      ar: { title: "إِفْرِيقِيَا", kindLabel: "قَارَّةٌ", periodLabel: "عَبْرَ الْبَحْرِ الْأَحْمَرِ", summary: "إِفْرِيقِيَا قَارَّةٌ كَبِيرَةٌ جِدًّا، تَقَعُ عَبْرَ الْبَحْرِ الْأَحْمَرِ مِنْ بِلَادِ الْعَرَبِ. وَكَانَ كَثِيرٌ مِنَ الْعَبِيدِ فِي مَكَّةَ مَجْلُوبِينَ مِنْ إِفْرِيقِيَا.", more: "مِصْرُ وَالْحَبَشَةُ كِلْتَاهُمَا فِي إِفْرِيقِيَا." },
    },
    focus: medFeature('africa', 10, 20, 1, { view: { north: 40, west: -20, widthDegrees: 75 } }),
    picture: { folder: "mecca", name: "africa" },
    sources: ["TDV İslâm Ansiklopedisi: Afrika"],
  }),
  defineEntity({
    id: "mecca-arafat", kind: "landmark",
    aliases: { en: ["Arafat"], ar: ["عرفات"] },
    copy: {
      en: { title: "Arafat", kindLabel: "Plain", periodLabel: "Near Mecca", summary: "Arafat is a wide plain east of Mecca. Even before Islam, pilgrims stood there in the Hajj season.", more: "Standing at Arafat is still the most important part of Hajj." },
      ar: { title: "عَرَفَاتٌ", kindLabel: "سَهْلٌ", periodLabel: "قُرْبَ مَكَّةَ", summary: "عَرَفَاتٌ سَهْلٌ وَاسِعٌ شَرْقَ مَكَّةَ. وَحَتَّى قَبْلَ الْإِسْلَامِ، كَانَ الْحُجَّاجُ يَقِفُونَ فِيهِ فِي مَوْسِمِ الْحَجِّ.", more: "مَا زَالَ الْوُقُوفُ بِعَرَفَةَ أَهَمَّ أَرْكَانِ الْحَجِّ." },
    },
    focus: medPoint(21.35, 39.98, CITY_ZOOM),
    picture: { folder: "mecca", name: "arafat" },
    sources: ["TDV İslâm Ansiklopedisi: Arafat"],
  }),
  defineEntity({
    id: "mecca-safa-and-marwa", kind: "landmark", tr: "Safa ve Merve",
    aliases: { en: ["Safa and Marwa","Safa and Marwah"], ar: ["الصفا والمروة"] },
    copy: {
      en: { title: "Safa and Marwa", kindLabel: "Two hills", periodLabel: "Mecca", summary: "Safa and Marwa are two small hills in Mecca, near the Ka’ba. Even before Islam, pilgrims went back and forth between them.", more: "This walk, called sa’y, remembers Hagar’s search for water for her son Ishmael (pbuh)." },
      ar: { title: "الصَّفَا وَالْمَرْوَةُ", kindLabel: "تَلَّانِ", periodLabel: "مَكَّةُ", summary: "الصَّفَا وَالْمَرْوَةُ تَلَّانِ صَغِيرَانِ فِي مَكَّةَ، قُرْبَ الْكَعْبَةِ. وَحَتَّى قَبْلَ الْإِسْلَامِ، كَانَ الْحُجَّاجُ يَسْعَوْنَ بَيْنَهُمَا.", more: "يُسَمَّى هَذَا الْمَشْيُ السَّعْيَ، وَهُوَ يُذَكِّرُ بِسَعْيِ هَاجَرَ بَحْثًا عَنِ الْمَاءِ لِابْنِهَا إِسْمَاعِيلَ عَلَيْهِ السَّلَامُ." },
    },
    focus: medPoint(21.42, 39.83, CITY_ZOOM),
    picture: { folder: "mecca", name: "safa-and-marwa" },
    sources: ["TDV İslâm Ansiklopedisi: Safâ","TDV İslâm Ansiklopedisi: Merve"],
  }),
  defineEntity({
    id: "mecca-ukaz", kind: "landmark", tr: "Ukâz Panayırı",
    aliases: { en: ["Ukaz"], ar: ["عكاظ"] },
    copy: {
      en: { title: "Ukaz", kindLabel: "Trade fair", periodLabel: "Before Islam", summary: "Ukaz was a big trade fair east of Mecca before Islam. People came to it in the Hajj season, and after the fair they went to Arafat.", more: "Famous poets read their poems at Ukaz." },
      ar: { title: "سُوقُ عُكَاظٍ", kindLabel: "سُوقٌ مَوْسِمِيَّةٌ", periodLabel: "قَبْلَ الْإِسْلَامِ", summary: "عُكَاظٌ سُوقٌ تِجَارِيَّةٌ كُبْرَى كَانَتْ تُقَامُ شَرْقَ مَكَّةَ قَبْلَ الْإِسْلَامِ. وَكَانَ النَّاسُ يَحْضُرُونَهَا فِي مَوْسِمِ الْحَجِّ، ثُمَّ يَذْهَبُونَ بَعْدَهَا إِلَى عَرَفَاتٍ.", more: "كَانَ الشُّعَرَاءُ الْمَشْهُورُونَ يُلْقُونَ قَصَائِدَهُمْ فِي عُكَاظٍ." },
    },
    focus: medPoint(21.6, 40.5, CITY_ZOOM),
    picture: { folder: "mecca", name: "ukaz" },
    sources: ["TDV İslâm Ansiklopedisi: Ukâz"],
  }),
  defineEntity({
    id: "mecca-majannah", kind: "landmark", tr: "Mecenne Panayırı",
    aliases: { en: ["Majannah"], ar: ["مجنة"] },
    copy: {
      en: { title: "Majannah", kindLabel: "Trade fair", periodLabel: "Before Islam", summary: "Majannah was a trade fair near Mecca before Islam. It was held in the Hajj season, like Ukaz and Dhul-Majaz.", more: "People usually went there after the Ukaz fair." },
      ar: { title: "سُوقُ مَجَنَّةَ", kindLabel: "سُوقٌ مَوْسِمِيَّةٌ", periodLabel: "قَبْلَ الْإِسْلَامِ", summary: "مَجَنَّةُ سُوقٌ تِجَارِيَّةٌ كَانَتْ تُقَامُ قُرْبَ مَكَّةَ قَبْلَ الْإِسْلَامِ. وَكَانَتْ فِي مَوْسِمِ الْحَجِّ، مِثْلَ عُكَاظٍ وَذِي الْمَجَازِ.", more: "كَانَ النَّاسُ يَذْهَبُونَ إِلَيْهَا عَادَةً بَعْدَ سُوقِ عُكَاظٍ." },
    },
    focus: medPoint(21.45, 39.62, CITY_ZOOM),
    picture: { folder: "mecca", name: "majannah" },
    sources: ["TDV İslâm Ansiklopedisi: Mecenne"],
  }),
  defineEntity({
    id: "mecca-dhul-majaz", kind: "landmark", tr: "Zülmecâz Panayırı",
    aliases: { en: ["Dhul-Majaz"], ar: ["ذي المجاز"] },
    copy: {
      en: { title: "Dhul-Majaz", kindLabel: "Trade fair", periodLabel: "Before Islam", summary: "Dhul-Majaz was a trade fair near Arafat, not far from Mecca. It was held in the Hajj season, and from there people went to Arafat.", more: "It was the last of the three big fairs before Hajj." },
      ar: { title: "سُوقُ ذِي الْمَجَازِ", kindLabel: "سُوقٌ مَوْسِمِيَّةٌ", periodLabel: "قَبْلَ الْإِسْلَامِ", summary: "ذُو الْمَجَازِ سُوقٌ تِجَارِيَّةٌ كَانَتْ تُقَامُ قُرْبَ عَرَفَاتٍ، غَيْرَ بَعِيدٍ عَنْ مَكَّةَ. وَكَانَتْ فِي مَوْسِمِ الْحَجِّ، وَمِنْهَا كَانَ النَّاسُ يَذْهَبُونَ إِلَى عَرَفَاتٍ.", more: "كَانَتْ آخِرَ الْأَسْوَاقِ الثَّلَاثِ الْكُبْرَى قَبْلَ الْحَجِّ." },
    },
    focus: medPoint(21.38, 40.02, CITY_ZOOM),
    picture: { folder: "mecca", name: "dhul-majaz" },
    sources: ["TDV İslâm Ansiklopedisi: Zülmecâz"],
  }),
  defineEntity({
    id: "mecca-silk-road", kind: "region", tr: "İpek Yolu",
    aliases: { en: ["Silk Road"], ar: ["طريق الحرير"] },
    copy: {
      en: { title: "Silk Road", kindLabel: "Trade route", periodLabel: "East to West", summary: "The Silk Road was the most important trade route from the East to the Mediterranean. In the 6th century, wars closed it, so the routes through Arabia became more important.", more: "It got its name from Chinese silk." },
      ar: { title: "طَرِيقُ الْحَرِيرِ", kindLabel: "طَرِيقٌ تِجَارِيٌّ", periodLabel: "مِنَ الشَّرْقِ إِلَى الْغَرْبِ", summary: "كَانَ طَرِيقُ الْحَرِيرِ أَهَمَّ طَرِيقٍ تِجَارِيٍّ بَيْنَ الشَّرْقِ وَالْبَحْرِ الْأَبْيَضِ الْمُتَوَسِّطِ. وَفِي الْقَرْنِ السَّادِسِ أَغْلَقَتْهُ الْحُرُوبُ، فَصَارَتِ الطُّرُقُ عَبْرَ بِلَادِ الْعَرَبِ أَكْثَرَ أَهَمِّيَّةً.", more: "سُمِّيَ بِهَذَا الِاسْمِ نِسْبَةً إِلَى الْحَرِيرِ الصِّينِيِّ." },
    },
    focus: medFeature('silk-road', 38, 65, 1, { view: { north: 50, west: 30, widthDegrees: 85 } }),
    picture: { folder: "mecca", name: "silk-road" },
    sources: ["TDV İslâm Ansiklopedisi: İpek Yolu"],
  }),
  defineEntity({
    id: "mecca-red-sea", kind: "sea", tr: "Kızıldeniz",
    aliases: { en: ["Red Sea"], ar: ["البحر الأحمر"] },
    copy: {
      en: { title: "Red Sea", kindLabel: "Sea", periodLabel: "West of Arabia", summary: "The Red Sea is a long, narrow sea between Arabia and Africa. In the 6th century, the trade route on the Red Sea became very important.", more: "It is famous for its colorful coral reefs." },
      ar: { title: "الْبَحْرُ الْأَحْمَرُ", kindLabel: "بَحْرٌ", periodLabel: "غَرْبَ شِبْهِ الْجَزِيرَةِ الْعَرَبِيَّةِ", summary: "الْبَحْرُ الْأَحْمَرُ بَحْرٌ طَوِيلٌ ضَيِّقٌ بَيْنَ شِبْهِ الْجَزِيرَةِ الْعَرَبِيَّةِ وَإِفْرِيقِيَا. وَفِي الْقَرْنِ السَّادِسِ، صَارَ طَرِيقُ التِّجَارَةِ عَبْرَهُ مُهِمًّا جِدًّا.", more: "يَشْتَهِرُ بِشِعَابِهِ الْمَرْجَانِيَّةِ الْمُلَوَّنَةِ." },
    },
    focus: medFeature('red-sea', 20, 38.5, 1),
    picture: { folder: "andalus", name: "red-sea" },
    sources: ["TDV İslâm Ansiklopedisi: Kızıldeniz"],
  }),
  defineEntity({
    id: "mecca-mediterranean", kind: "sea", tr: "Akdeniz",
    aliases: { en: ["Mediterranean"], ar: ["البحر الأبيض المتوسط"] },
    copy: {
      en: { title: "Mediterranean Sea", kindLabel: "Sea", periodLabel: "Between three continents", summary: "The Mediterranean is a large sea between Europe, Asia and Africa. Trade routes from the East reached its coasts.", more: "Great empires, like the Roman Empire, grew up around this sea." },
      ar: { title: "الْبَحْرُ الْأَبْيَضُ الْمُتَوَسِّطُ", kindLabel: "بَحْرٌ", periodLabel: "بَيْنَ ثَلَاثِ قَارَّاتٍ", summary: "الْبَحْرُ الْأَبْيَضُ الْمُتَوَسِّطُ بَحْرٌ كَبِيرٌ بَيْنَ أُورُوبَّا وَآسِيَا وَإِفْرِيقِيَا. وَكَانَتْ طُرُقُ التِّجَارَةِ الْقَادِمَةُ مِنَ الشَّرْقِ تَصِلُ إِلَى سَوَاحِلِهِ.", more: "نَشَأَتْ حَوْلَهُ إِمْبِرَاطُورِيَّاتٌ عَظِيمَةٌ، مِثْلُ الْإِمْبِرَاطُورِيَّةِ الرُّومَانِيَّةِ." },
    },
    focus: medFeature('mediterranean', 35, 18, 1),
    picture: { folder: "andalus", name: "mediterranean" },
    sources: ["TDV İslâm Ansiklopedisi: Akdeniz"],
  }),
  defineEntity({
    id: "mecca-persian-gulf", kind: "sea", tr: "Basra Körfezi",
    aliases: { en: ["Arabian/Persian Gulf"], ar: ["الخليج العربي"] },
    copy: {
      en: { title: "Arabian Gulf (Persian Gulf)", kindLabel: "Gulf", periodLabel: "East of Arabia", summary: "The Arabian Gulf, also called the Persian Gulf, is a sea east of the Arabian Peninsula. It lies between Arabia and Iran.", more: "For a very long time, people dived there for pearls." },
      ar: { title: "الْخَلِيجُ الْعَرَبِيُّ", kindLabel: "خَلِيجٌ", periodLabel: "شَرْقَ شِبْهِ الْجَزِيرَةِ الْعَرَبِيَّةِ", summary: "الْخَلِيجُ الْعَرَبِيُّ، وَيُسَمَّى أَيْضًا الْخَلِيجَ الْفَارِسِيَّ، بَحْرٌ يَقَعُ شَرْقَ شِبْهِ الْجَزِيرَةِ الْعَرَبِيَّةِ، بَيْنَ بِلَادِ الْعَرَبِ وَإِيرَانَ.", more: "كَانَ النَّاسُ مُنْذُ زَمَنٍ طَوِيلٍ يَغُوصُونَ فِيهِ بَحْثًا عَنِ اللُّؤْلُؤِ." },
    },
    focus: medFeature('persian-gulf', 27, 51.5, 1),
    picture: { folder: "mecca", name: "persian-gulf" },
    sources: ["TDV İslâm Ansiklopedisi: Basra Körfezi"],
  }),
  defineEntity({
    id: "mecca-indian-ocean", kind: "sea", tr: "Hint Okyanusu",
    aliases: { en: ["Indian Ocean"], ar: ["المحيط الهندي"] },
    copy: {
      en: { title: "Indian Ocean", kindLabel: "Ocean", periodLabel: "South of Arabia", summary: "The Indian Ocean is the big ocean south of the Arabian Peninsula. Ships carried goods across it between India, Africa and Arabia.", more: "It is the third largest ocean in the world." },
      ar: { title: "الْمُحِيطُ الْهِنْدِيُّ", kindLabel: "مُحِيطٌ", periodLabel: "جَنُوبَ شِبْهِ الْجَزِيرَةِ الْعَرَبِيَّةِ", summary: "الْمُحِيطُ الْهِنْدِيُّ مُحِيطٌ كَبِيرٌ يَقَعُ جَنُوبَ شِبْهِ الْجَزِيرَةِ الْعَرَبِيَّةِ. وَكَانَتِ السُّفُنُ تَنْقُلُ الْبَضَائِعَ عَبْرَهُ بَيْنَ الْهِنْدِ وَإِفْرِيقِيَا وَبِلَادِ الْعَرَبِ.", more: "هُوَ ثَالِثُ أَكْبَرِ مُحِيطٍ فِي الْعَالَمِ." },
    },
    focus: medFeature('indian-ocean', 5, 70, 1, { view: { north: 30, west: 35, widthDegrees: 70 } }),
    picture: { folder: "mecca", name: "indian-ocean" },
    sources: [],
  }),
  defineEntity({
    id: "mecca-zamzam", kind: "landmark", tr: "Zemzem",
    aliases: { en: ["Zamzam"], ar: ["زمزم"] },
    copy: {
      en: { title: "Zamzam", kindLabel: "Well", periodLabel: "Mecca", summary: "Zamzam is a well of water in Mecca, near the Ka’ba. After it was found, people began to live in the empty valley of Mecca.", more: "Pilgrims still drink Zamzam water today." },
      ar: { title: "زَمْزَمُ", kindLabel: "بِئْرٌ", periodLabel: "مَكَّةُ", summary: "زَمْزَمُ بِئْرُ مَاءٍ فِي مَكَّةَ، قُرْبَ الْكَعْبَةِ. وَبَعْدَ اكْتِشَافِ مَائِهَا، بَدَأَ النَّاسُ يَسْكُنُونَ وَادِيَ مَكَّةَ الْخَالِيَ.", more: "مَا زَالَ الْحُجَّاجُ يَشْرَبُونَ مَاءَ زَمْزَمَ إِلَى الْيَوْمِ." },
    },
    focus: medPoint(21.42, 39.83, CITY_ZOOM),
    picture: { folder: "mecca", name: "zamzam" },
    sources: ["TDV İslâm Ansiklopedisi: Zemzem"],
  }),
  defineEntity({
    id: "mecca-kaaba-7th-century", kind: "landmark", tr: "Kâbe",
    aliases: { en: ["Ka’ba"], ar: ["الكعبة"] },
    copy: {
      en: { title: "Ka’ba", kindLabel: "Holy building", periodLabel: "Mecca", summary: "The Ka’ba is the holy House of Allah in Mecca. Abraham (pbuh) and his son Ishmael (pbuh) rebuilt it, but before Islam people put idols in and around it.", more: "Muslims all over the world face the Ka’ba when they pray." },
      ar: { title: "الْكَعْبَةُ الْمُشَرَّفَةُ", kindLabel: "بَيْتٌ مُقَدَّسٌ", periodLabel: "مَكَّةُ", summary: "الْكَعْبَةُ الْمُشَرَّفَةُ بَيْتُ اللَّهِ فِي مَكَّةَ. أَعَادَ بِنَاءَهَا إِبْرَاهِيمُ عَلَيْهِ السَّلَامُ وَابْنُهُ إِسْمَاعِيلُ عَلَيْهِ السَّلَامُ، وَلَكِنَّ النَّاسَ وَضَعُوا الْأَصْنَامَ فِيهَا وَحَوْلَهَا قَبْلَ الْإِسْلَامِ.", more: "يَتَوَجَّهُ الْمُسْلِمُونَ فِي كُلِّ الْعَالَمِ إِلَى الْكَعْبَةِ فِي صَلَاتِهِمْ." },
    },
    focus: medPoint(21.42, 39.83, CITY_ZOOM),
    picture: { folder: "mecca", name: "kaaba-7th-century" },
    sources: ["TDV İslâm Ansiklopedisi: Kâbe"],
  }),
  defineEntity({
    id: "mecca-quraysh", kind: "tribe", tr: "Kureyş",
    aliases: { en: ["Quraysh"], ar: ["قريش"] },
    copy: {
      en: { title: "Quraysh", kindLabel: "Tribe", periodLabel: "5th–7th century · Mecca", summary: "The Quraysh were the tribe that ruled Mecca and the Ka’ba from the 5th century. Their rich merchants sent big trade caravans to many lands.", more: "Prophet Muhammad (pbuh) was born into the Quraysh tribe." },
      ar: { title: "قُرَيْشٌ", kindLabel: "قَبِيلَةٌ", periodLabel: "الْقَرْنُ الْخَامِسُ إِلَى السَّابِعِ · مَكَّةُ", summary: "قُرَيْشٌ قَبِيلَةٌ عَرَبِيَّةٌ حَكَمَتْ مَكَّةَ وَالْكَعْبَةَ مُنْذُ الْقَرْنِ الْخَامِسِ. وَكَانَ تُجَّارُهَا الْأَغْنِيَاءُ يُرْسِلُونَ قَوَافِلَ تِجَارِيَّةً كَبِيرَةً إِلَى بِلَادٍ كَثِيرَةٍ.", more: "وُلِدَ النَّبِيُّ مُحَمَّدٌ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فِي قَبِيلَةِ قُرَيْشٍ." },
    },
    focus: medFeature('mecca-area', 21.42, 39.83, 1),
    picture: { folder: "mecca", name: "quraysh" },
    sources: ["TDV İslâm Ansiklopedisi: Kureyş"],
  }),
  defineEntity({
    id: "mecca-jurhum", kind: "tribe", tr: "Cürhümlüler",
    aliases: { en: ["Jurhum"], ar: ["جرهم"] },
    copy: {
      en: { title: "Jurhum tribe", kindLabel: "Tribe", periodLabel: "Ancient times · Mecca", summary: "The Jurhumites were a tribe from Yemen. They settled in Mecca after Zamzam water was found, and Ishmael (pbuh) learned Arabic from them.", more: "Ishmael (pbuh) married a woman from this tribe." },
      ar: { title: "جُرْهُمٌ", kindLabel: "قَبِيلَةٌ", periodLabel: "زَمَنٌ قَدِيمٌ · مَكَّةُ", summary: "جُرْهُمٌ قَبِيلَةٌ جَاءَتْ مِنَ الْيَمَنِ، وَاسْتَقَرَّتْ فِي مَكَّةَ بَعْدَ اكْتِشَافِ مَاءِ زَمْزَمَ. وَمِنْهُمْ تَعَلَّمَ إِسْمَاعِيلُ عَلَيْهِ السَّلَامُ اللُّغَةَ الْعَرَبِيَّةَ.", more: "تَزَوَّجَ إِسْمَاعِيلُ عَلَيْهِ السَّلَامُ امْرَأَةً مِنْ هَذِهِ الْقَبِيلَةِ." },
    },
    focus: medFeature('mecca-area', 21.42, 39.83, 1, { arrows: [{ from: [15.4, 44.2], to: [21.42, 39.83] }] }),
    picture: { folder: "mecca", name: "jurhum" },
    sources: ["TDV İslâm Ansiklopedisi: Cürhüm"],
  }),
  defineEntity({
    id: "mecca-khuzaa", kind: "tribe", tr: "Huzâa",
    aliases: { en: ["Khuza’a"], ar: ["خزاعة","خزاعيون"] },
    copy: {
      en: { title: "Khuza’a tribe", kindLabel: "Tribe", periodLabel: "Before the Quraysh · Mecca", summary: "The Khuza’a were an Arab tribe that defeated the Jurhum tribe and ruled Mecca. In their time, people forgot the religion of Abraham (pbuh) and began to worship idols.", more: "Later, the Quraysh took control of Mecca and the Ka’ba from them." },
      ar: { title: "خُزَاعَةُ", kindLabel: "قَبِيلَةٌ", periodLabel: "قَبْلَ قُرَيْشٍ · مَكَّةُ", summary: "خُزَاعَةُ قَبِيلَةٌ عَرَبِيَّةٌ هَزَمَتْ قَبِيلَةَ جُرْهُمٍ وَحَكَمَتْ مَكَّةَ. وَفِي زَمَنِهَا نَسِيَ النَّاسُ دِينَ إِبْرَاهِيمَ عَلَيْهِ السَّلَامُ وَبَدَؤُوا يَعْبُدُونَ الْأَصْنَامَ.", more: "ثُمَّ انْتَزَعَتْ قُرَيْشٌ مِنْهَا حُكْمَ مَكَّةَ وَالْكَعْبَةِ." },
    },
    focus: medFeature('mecca-area', 21.42, 39.83, 1),
    picture: { folder: "mecca", name: "khuzaa" },
    sources: ["TDV İslâm Ansiklopedisi: Huzâa"],
  }),
  defineEntity({
    id: "mecca-pre-islamic-arabs", kind: "people", tr: "Araplar",
    aliases: { en: ["Arabs"], ar: ["كان العرب","قبول العرب","عرب الجاهلية","لعربي على أعجمي"] },
    copy: {
      en: { title: "Arabs", kindLabel: "People", periodLabel: "Before Islam", summary: "The Arabs are the people of the Arabian Peninsula. Before Islam, they lived in tribes, and most of them worshipped idols.", more: "Their language, Arabic, is the language of the Qur’an." },
      ar: { title: "الْعَرَبُ", kindLabel: "شَعْبٌ", periodLabel: "قَبْلَ الْإِسْلَامِ", summary: "الْعَرَبُ هُمْ أَهْلُ شِبْهِ الْجَزِيرَةِ الْعَرَبِيَّةِ. وَقَبْلَ الْإِسْلَامِ كَانُوا يَعِيشُونَ فِي قَبَائِلَ، وَكَانَ أَكْثَرُهُمْ يَعْبُدُونَ الْأَصْنَامَ.", more: "لُغَتُهُمُ الْعَرَبِيَّةُ هِيَ لُغَةُ الْقُرْآنِ الْكَرِيمِ." },
    },
    focus: medFeature('arabian-peninsula', 23, 45, 1),
    picture: { folder: "mecca", name: "pre-islamic-arabs" },
    sources: ["TDV İslâm Ansiklopedisi: Arap","TDV İslâm Ansiklopedisi: Câhiliye"],
  }),
  defineEntity({
    id: "mecca-hanifs", kind: "people", tr: "Hanîfler",
    aliases: { en: ["Hanifs"], ar: ["حنفاء"] },
    copy: {
      en: { title: "Hanifs", kindLabel: "Believers in one God", periodLabel: "Before Islam", summary: "The Hanifs were a few people before Islam who followed the old religion of Abraham (pbuh). They believed only in Allah and did not worship idols.", more: "The Qur’an calls Abraham (pbuh) a hanif." },
      ar: { title: "الْحُنَفَاءُ", kindLabel: "مُوَحِّدُونَ", periodLabel: "قَبْلَ الْإِسْلَامِ", summary: "الْحُنَفَاءُ أَشْخَاصٌ قَلِيلُونَ قَبْلَ الْإِسْلَامِ، اتَّبَعُوا دِينَ إِبْرَاهِيمَ عَلَيْهِ السَّلَامُ الْقَدِيمَ. فَكَانُوا يُؤْمِنُونَ بِاللَّهِ وَحْدَهُ، وَلَا يَعْبُدُونَ الْأَصْنَامَ.", more: "وَصَفَ الْقُرْآنُ الْكَرِيمُ إِبْرَاهِيمَ عَلَيْهِ السَّلَامُ بِأَنَّهُ كَانَ حَنِيفًا." },
    },
    focus: medFeature('mecca-area', 21.42, 39.83, 1),
    picture: { folder: "mecca", name: "hanifs" },
    sources: ["TDV İslâm Ansiklopedisi: Hanîf"],
  }),
  defineEntity({
    id: "mecca-byzantine-empire", kind: "empire", tr: "Bizans İmparatorluğu",
    aliases: { en: ["Byzantine","Byzantium"], ar: ["بيزنطية","بيزنطة"] },
    copy: {
      en: { title: "Byzantine Empire", kindLabel: "Empire", periodLabel: "6th–7th century", summary: "The Byzantine Empire was a large Christian empire north of Arabia. Its capital was Constantinople, and it ruled lands such as Egypt.", more: "It was the eastern part of the old Roman Empire." },
      ar: { title: "الْإِمْبِرَاطُورِيَّةُ الْبِيزَنْطِيَّةُ", kindLabel: "إِمْبِرَاطُورِيَّةٌ", periodLabel: "الْقَرْنَانِ السَّادِسُ وَالسَّابِعُ", summary: "الْإِمْبِرَاطُورِيَّةُ الْبِيزَنْطِيَّةُ دَوْلَةٌ مَسِيحِيَّةٌ كَبِيرَةٌ كَانَتْ شَمَالَ بِلَادِ الْعَرَبِ. وَكَانَتْ عَاصِمَتُهَا الْقُسْطَنْطِينِيَّةَ، وَحَكَمَتْ بِلَادًا مِثْلَ مِصْرَ.", more: "كَانَتِ الْجُزْءَ الشَّرْقِيَّ مِنَ الْإِمْبِرَاطُورِيَّةِ الرُّومَانِيَّةِ الْقَدِيمَةِ." },
    },
    focus: medFeature('byzantine-empire', 39, 32, 1),
    picture: { folder: "mecca", name: "byzantine-empire" },
    sources: ["TDV İslâm Ansiklopedisi: Bizans"],
  }),
  defineEntity({
    id: "mecca-sassanids", kind: "empire", tr: "Sâsânîler",
    aliases: { en: ["Sassanid","Persians"], ar: ["ساسانيون","ساسانيين","ساسانية","الفرس"] },
    copy: {
      en: { title: "Sassanids (Persians)", kindLabel: "Empire", periodLabel: "Before Islam", summary: "The Sassanids ruled the Persians in a large empire east of Arabia. They were the great rivals of the Byzantine Empire.", more: "Their capital was Ctesiphon, near today’s Baghdad." },
      ar: { title: "السَّاسَانِيُّونَ (الْفُرْسُ)", kindLabel: "إِمْبِرَاطُورِيَّةٌ", periodLabel: "قَبْلَ الْإِسْلَامِ", summary: "حَكَمَ السَّاسَانِيُّونَ الْفُرْسَ فِي إِمْبِرَاطُورِيَّةٍ كَبِيرَةٍ شَرْقَ بِلَادِ الْعَرَبِ. وَكَانُوا الْمُنَافِسِينَ الْكِبَارَ لِلْإِمْبِرَاطُورِيَّةِ الْبِيزَنْطِيَّةِ.", more: "كَانَتْ عَاصِمَتُهُمُ الْمَدَائِنَ، قُرْبَ بَغْدَادَ الْيَوْمَ." },
    },
    focus: medFeature('sassanid-empire', 32.5, 53, 1, { view: { north: 46, west: 22, widthDegrees: 50 } }),
    picture: { folder: "mecca", name: "sassanids" },
    sources: ["TDV İslâm Ansiklopedisi: Sâsânîler"],
  }),
  defineEntity({
    id: "mecca-roman-empire", kind: "empire", tr: "Roma İmparatorluğu",
    aliases: { en: ["Roman Empire"], ar: ["الإمبراطورية الرومانية"] },
    copy: {
      en: { title: "Roman Empire", kindLabel: "Empire", periodLabel: "Ancient times", summary: "The Roman Empire was a great empire around the Mediterranean Sea. Its western part fell in 476, and this is often taken as the start of the Middle Ages.", more: "The city of Rome, in Italy, was its first capital." },
      ar: { title: "الْإِمْبِرَاطُورِيَّةُ الرُّومَانِيَّةُ", kindLabel: "إِمْبِرَاطُورِيَّةٌ", periodLabel: "الْعُصُورُ الْقَدِيمَةُ", summary: "الْإِمْبِرَاطُورِيَّةُ الرُّومَانِيَّةُ دَوْلَةٌ عَظِيمَةٌ امْتَدَّتْ حَوْلَ الْبَحْرِ الْأَبْيَضِ الْمُتَوَسِّطِ. وَسَقَطَ جُزْؤُهَا الْغَرْبِيُّ عَامَ أَرْبَعِمِئَةٍ وَسِتَّةٍ وَسَبْعِينَ لِلْمِيلَادِ، وَيُعَدُّ ذَلِكَ بِدَايَةَ الْعُصُورِ الْوُسْطَى.", more: "كَانَتْ مَدِينَةُ رُومَا فِي إِيطَالِيَا عَاصِمَتَهَا الْأُولَى." },
    },
    focus: medFeature('roman-empire', 41, 13, 1, { view: { north: 53, west: -12, widthDegrees: 60 } }),
    picture: { folder: "mecca", name: "roman-empire" },
    sources: ["TDV İslâm Ansiklopedisi: Roma"],
  }),
  defineEntity({
    id: "mecca-ottomans-15th-century", kind: "people", tr: "Osmanlı Türkleri",
    aliases: { en: ["Ottoman Turks"], ar: ["الأتراك العثمانيين"] },
    copy: {
      en: { title: "Ottoman Turks", kindLabel: "People", periodLabel: "15th century", summary: "The Ottoman Turks built a great state in Anatolia and the Balkans. In 1453 they conquered Constantinople, and this is often taken as the end of the Middle Ages.", more: "Sultan Mehmed II (the Conqueror) led them in the conquest of Constantinople." },
      ar: { title: "الْأَتْرَاكُ الْعُثْمَانِيُّونَ", kindLabel: "شَعْبٌ وَدَوْلَةٌ", periodLabel: "الْقَرْنُ الْخَامِسَ عَشَرَ", summary: "أَسَّسَ الْأَتْرَاكُ الْعُثْمَانِيُّونَ دَوْلَةً عَظِيمَةً فِي الْأَنَاضُولِ وَالْبَلْقَانِ. وَفَتَحُوا الْقُسْطَنْطِينِيَّةَ عَامَ أَلْفٍ وَأَرْبَعِمِئَةٍ وَثَلَاثَةٍ وَخَمْسِينَ لِلْمِيلَادِ، وَيُعَدُّ ذَلِكَ نِهَايَةَ الْعُصُورِ الْوُسْطَى.", more: "قَادَهُمُ السُّلْطَانُ مُحَمَّدٌ الْفَاتِحُ فِي فَتْحِ الْقُسْطَنْطِينِيَّةِ." },
    },
    focus: medFeature('ottoman-1453', 40.5, 28, 1),
    picture: { folder: "mecca", name: "ottomans-15th-century" },
    sources: ["TDV İslâm Ansiklopedisi: Osmanlılar"],
  }),
  defineEntity({
    id: "mecca-hilf-al-fudul", kind: "people", tr: "Hilfü'l-Fudûl",
    aliases: { en: ["Hilf al-Fudul","Hilf al-Fudul"], ar: ["حلف الفضول"] },
    copy: {
      en: { title: "Hilf al-Fudul", kindLabel: "Alliance", periodLabel: "Before Islam · Mecca", summary: "Hilf al-Fudul was an agreement made by some Quraysh tribes in Mecca to help people who were treated unfairly. Young Muhammad (pbuh) also took part in it.", more: "The meeting was held in the house of Abdullah ibn Jud’an in Mecca." },
      ar: { title: "حِلْفُ الْفُضُولِ", kindLabel: "حِلْفٌ", periodLabel: "قَبْلَ الْإِسْلَامِ · مَكَّةُ", summary: "حِلْفُ الْفُضُولِ اتِّفَاقٌ عَقَدَتْهُ بَعْضُ قَبَائِلِ قُرَيْشٍ فِي مَكَّةَ لِنُصْرَةِ الْمَظْلُومِينَ. وَقَدْ حَضَرَهُ مُحَمَّدٌ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فِي شَبَابِهِ.", more: "عُقِدَ هَذَا الْحِلْفُ فِي بَيْتِ عَبْدِ اللَّهِ بْنِ جُدْعَانَ فِي مَكَّةَ." },
    },
    focus: medPoint(21.42, 39.83, CITY_ZOOM),
    picture: { folder: "mecca", name: "hilf-al-fudul" },
    sources: ["TDV İslâm Ansiklopedisi: Hilfülfudûl"],
  }),
  defineEntity({
    id: "mecca-umayya-ibn-khalaf", kind: "person", tr: "Ümeyye b. Halef",
    aliases: { en: ["Umayya"], ar: ["أمية"] },
    copy: {
      en: { title: "Umayya ibn Khalaf", kindLabel: "Person", periodLabel: "7th century · Mecca", summary: "Umayya ibn Khalaf was one of the rich and powerful leaders of Mecca. He was Bilal’s master and hurt him badly because Bilal became a Muslim.", more: "He was from the Quraysh tribe." },
      ar: { title: "أُمَيَّةُ بْنُ خَلَفٍ", kindLabel: "شَخْصٌ", periodLabel: "الْقَرْنُ السَّابِعُ · مَكَّةُ", summary: "كَانَ أُمَيَّةُ بْنُ خَلَفٍ مِنْ أَغْنَى زُعَمَاءِ مَكَّةَ وَأَقْوَاهُمْ. وَكَانَ سَيِّدَ بِلَالٍ، فَعَذَّبَهُ عَذَابًا شَدِيدًا لِأَنَّهُ أَسْلَمَ.", more: "كَانَ مِنْ قَبِيلَةِ قُرَيْشٍ." },
    },
    focus: medPoint(21.42, 39.83, CITY_ZOOM),
    picture: { folder: "mecca", name: "umayya-ibn-khalaf" },
    sources: ["TDV İslâm Ansiklopedisi: Ümeyye b. Khalaf"],
  }),
  defineEntity({
    id: "mecca-ubayy-ibn-khalaf", kind: "person", tr: "Übey b. Halef",
    aliases: { en: ["Ubayy"], ar: ["أبي بن خلف"] },
    copy: {
      en: { title: "Ubayy ibn Khalaf", kindLabel: "Person", periodLabel: "Before Islam · Mecca", summary: "Ubayy ibn Khalaf was one of the leading men of Mecca. He did not pay a merchant for his goods, but he paid at once when Hilf al-Fudul stood with the merchant.", more: "He was a brother of Umayya ibn Khalaf." },
      ar: { title: "أُبَيُّ بْنُ خَلَفٍ", kindLabel: "شَخْصٌ", periodLabel: "قَبْلَ الْإِسْلَامِ · مَكَّةُ", summary: "كَانَ أُبَيُّ بْنُ خَلَفٍ مِنَ الشَّخْصِيَّاتِ الْبَارِزَةِ فِي مَكَّةَ. لَمْ يَدْفَعْ لِتَاجِرٍ ثَمَنَ بَضَائِعِهِ، ثُمَّ دَفَعَهُ فَوْرًا حِينَ وَقَفَ حِلْفُ الْفُضُولِ مَعَ التَّاجِرِ.", more: "كَانَ أَخًا لِأُمَيَّةَ بْنِ خَلَفٍ." },
    },
    focus: medPoint(21.42, 39.83, CITY_ZOOM),
    picture: { folder: "mecca", name: "ubayy-ibn-khalaf" },
    sources: ["TDV İslâm Ansiklopedisi: Übey b. Khalaf"],
  }),
  defineEntity({
    id: "mecca-abu-jahl", kind: "person", tr: "Ebû Cehil",
    aliases: { en: ["Abu Jahl"], ar: ["أبو جهل"] },
    copy: {
      en: { title: "Abu Jahl", kindLabel: "Person", periodLabel: "7th century · Mecca", summary: "Abu Jahl was one of the leading men of the Quraysh in Mecca. He strongly rejected Islam and led his tribe against it.", more: "His real name was Amr ibn Hisham." },
      ar: { title: "أَبُو جَهْلٍ", kindLabel: "شَخْصٌ", periodLabel: "الْقَرْنُ السَّابِعُ · مَكَّةُ", summary: "كَانَ أَبُو جَهْلٍ مِنْ أَبْرَزِ رِجَالِ قُرَيْشٍ فِي مَكَّةَ. رَفَضَ الْإِسْلَامَ بِشِدَّةٍ، وَقَادَ قَبِيلَتَهُ إِلَى مُعَارَضَتِهِ.", more: "كَانَ اسْمُهُ الْحَقِيقِيُّ عَمْرَو بْنَ هِشَامٍ." },
    },
    focus: medPoint(21.42, 39.83, CITY_ZOOM),
    picture: { folder: "mecca", name: "abu-jahl" },
    sources: ["TDV İslâm Ansiklopedisi: Ebû Cehil"],
  }),
];

export const MECCA_SET: EntityBookSet = {
  entities,
  chapters: {
    'mecca-a2': {
      1: ["mecca-mecca-7th-century","mecca-abyssinia"],
      2: ["mecca-mecca-7th-century"],
      3: ["mecca-mecca-7th-century","mecca-arabian-peninsula","mecca-abyssinia","mecca-umayya-ibn-khalaf"],
      4: ["mecca-mecca-7th-century","mecca-umayya-ibn-khalaf"],
      5: ["mecca-mecca-7th-century","mecca-umayya-ibn-khalaf"],
      7: ["mecca-umayya-ibn-khalaf"],
      8: ["mecca-mecca-7th-century","mecca-umayya-ibn-khalaf"],
      9: ["mecca-umayya-ibn-khalaf"],
      10: ["mecca-umayya-ibn-khalaf"],
      11: ["mecca-mecca-7th-century","mecca-medina-7th-century"],
      13: ["mecca-medina-7th-century","mecca-damascus-7th-century","mecca-pre-islamic-arabs"],
    },
    'mecca-b1': {
      1: ["mecca-mecca-7th-century","mecca-arabian-peninsula"],
      2: ["mecca-mecca-7th-century","mecca-kaaba-7th-century"],
      3: ["mecca-mecca-7th-century","mecca-mecca-valley-ancient","mecca-yemen-6th-century","mecca-zamzam","mecca-kaaba-7th-century","mecca-jurhum","mecca-pre-islamic-arabs"],
      4: ["mecca-mecca-7th-century","mecca-arabian-peninsula","mecca-palestine-ancient","mecca-india-ancient","mecca-indonesia-ancient","mecca-china-ancient","mecca-kaaba-7th-century","mecca-quraysh","mecca-jurhum","mecca-khuzaa","mecca-byzantine-empire","mecca-sassanids"],
      5: ["mecca-mecca-7th-century","mecca-abyssinia","mecca-yemen-6th-century","mecca-iraq-6th-century","mecca-quraysh","mecca-byzantine-empire"],
      6: ["mecca-mecca-7th-century","mecca-arabian-peninsula","mecca-arafat","mecca-safa-and-marwa","mecca-ukaz","mecca-majannah","mecca-dhul-majaz","mecca-kaaba-7th-century","mecca-quraysh"],
      7: ["mecca-mecca-7th-century","mecca-quraysh"],
      8: ["mecca-pre-islamic-arabs"],
      9: ["mecca-mecca-7th-century"],
      10: ["mecca-mecca-7th-century","mecca-arabian-peninsula","mecca-kaaba-7th-century","mecca-pre-islamic-arabs","mecca-hanifs"],
      11: ["mecca-mecca-7th-century","mecca-quraysh"],
      12: ["mecca-mecca-7th-century","mecca-arabian-peninsula","mecca-kaaba-7th-century","mecca-quraysh"],
      13: ["mecca-mecca-7th-century","mecca-abyssinia","mecca-umayya-ibn-khalaf"],
      15: ["mecca-mecca-7th-century","mecca-quraysh"],
    },
    'mecca-b2': {
      1: ["mecca-mecca-7th-century","mecca-constantinople-byzantine","mecca-arabian-peninsula","mecca-pre-islamic-arabs","mecca-byzantine-empire","mecca-sassanids","mecca-roman-empire","mecca-ottomans-15th-century"],
      2: ["mecca-mecca-7th-century","mecca-arabian-peninsula","mecca-india-ancient","mecca-red-sea","mecca-persian-gulf","mecca-indian-ocean","mecca-pre-islamic-arabs"],
      3: ["mecca-mecca-7th-century","mecca-mecca-valley-ancient","mecca-medina-7th-century","mecca-zamzam","mecca-kaaba-7th-century"],
      4: ["mecca-mecca-7th-century","mecca-arabian-peninsula","mecca-yemen-6th-century","mecca-palestine-ancient","mecca-india-ancient","mecca-indonesia-ancient","mecca-china-ancient","mecca-zamzam","mecca-kaaba-7th-century","mecca-quraysh","mecca-jurhum","mecca-khuzaa","mecca-pre-islamic-arabs","mecca-byzantine-empire","mecca-sassanids"],
      5: ["mecca-mecca-7th-century","mecca-abyssinia","mecca-yemen-6th-century","mecca-palestine-ancient","mecca-iraq-6th-century","mecca-syria-byzantine","mecca-egypt-byzantine","mecca-quraysh","mecca-byzantine-empire"],
      6: ["mecca-mecca-7th-century","mecca-arabian-peninsula","mecca-india-ancient","mecca-arafat","mecca-safa-and-marwa","mecca-ukaz","mecca-majannah","mecca-dhul-majaz","mecca-silk-road","mecca-red-sea","mecca-mediterranean","mecca-indian-ocean","mecca-kaaba-7th-century","mecca-quraysh","mecca-pre-islamic-arabs","mecca-byzantine-empire","mecca-sassanids"],
      7: ["mecca-mecca-7th-century","mecca-quraysh"],
      8: ["mecca-mecca-7th-century","mecca-quraysh","mecca-hilf-al-fudul","mecca-ubayy-ibn-khalaf"],
      9: ["mecca-mecca-7th-century","mecca-pre-islamic-arabs","mecca-hilf-al-fudul","mecca-ubayy-ibn-khalaf"],
      10: ["mecca-pre-islamic-arabs"],
      11: ["mecca-mecca-7th-century","mecca-damascus-7th-century","mecca-iraq-6th-century","mecca-syria-byzantine","mecca-africa"],
      12: ["mecca-mecca-7th-century","mecca-arabian-peninsula","mecca-kaaba-7th-century","mecca-pre-islamic-arabs","mecca-hanifs"],
      13: ["mecca-mecca-7th-century","mecca-arabian-peninsula","mecca-quraysh"],
      14: ["mecca-mecca-7th-century","mecca-quraysh"],
      15: ["mecca-mecca-7th-century","mecca-abyssinia","mecca-umayya-ibn-khalaf"],
      16: ["mecca-mecca-7th-century","mecca-quraysh"],
      17: ["mecca-mecca-7th-century","mecca-arabian-peninsula","mecca-quraysh","mecca-abu-jahl"],
    },
  },
};
