import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
  formatNumber: (num: number | string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'home.platformPositioning': 'Interactive Language & Values Library',
    'home.heroTitle': 'Learn Languages Through Sacred Stories, History and Heritage',
    'home.heroSubtitle': 'Explore interactive English and Arabic storybooks designed for students, teachers, and values-based education.',
    'home.exploreLibrary': 'Explore Library',
    'home.forTeachers': 'For Teachers',
    'home.statStories': '5 Stories',
    'home.statBooks': '15 Level-Based Books',
    'home.statLevels': 'A2–B2 Levels',
    'home.statLanguages': 'English & Arabic',
    'home.statGuides': 'Teacher & Self-Study Guides',
    'home.featInteractiveTitle': 'Interactive Reading',
    'home.featInteractiveDesc': 'Read paired text with contextual glossaries, real-time audio playback, and word tracking.',
    'home.featLevelsTitle': 'Level-Based Learning',
    'home.featLevelsDesc': 'Progress smoothly through graduated CEFR levels A2, B1, and B2 tailored for modern language development.',
    'home.featValuesTitle': 'Values Education',
    'home.featValuesDesc': 'Dignity, standing for truth, social justice, and loving-sincerity embedded directly within our narrative design.',
    'home.featTeachersTitle': 'Teacher Ready',
    'home.featTeachersDesc': 'Equipped with direct classroom launchers, modular lesson flows, assessment rubrics, and parenting links.',
    'home.collection1': 'Stories of the Prophets',
    'home.collection1Desc': 'Explore the lives of the prophets through interactive chapters, vocabulary, listening, exercises, and moral reflection.',
    'home.collection1Tag': 'Prophet Biography',
    'home.collection2': 'Islamic History & Civilization',
    'home.collection2Desc': 'Discover the cities, societies, and turning points that shaped the world in which Islam emerged.',
    'home.collection2Tag': 'Islamic History & Civilization',
    'home.collection3': 'Great Figures of Turkish-Islamic Heritage',
    'home.collection3Desc': 'Meet great poets, scholars, dervishes, and wise figures who shaped Turkish-Islamic thought, language, and moral imagination.',
    'home.collection3Tag': 'Turkish-Islamic Heritage',
    'home.explore': 'Explore',
    'home.collectionStories': 'stories',
    'home.selectToBegin': 'Click a story to select and begin your journey.',
    'nav.homeTitle': 'Stories of the Prophets',
    'nav.homeSubtitle': 'An interactive journey through faith, wisdom, and history.',
    'nav.back': 'Back',
    'nav.next': 'Next',
    'nav.finish': 'Finish',
    'nav.begin': 'Begin Journey',
    'nav.selectStory': 'Select a Story',
    'nav.chooseLevel': 'Choose Your Level',
    'nav.comingSoon': 'Coming Soon',
    'nav.meaning': 'Meaning',
    'nav.teacherGuide': 'Teacher Guide',
    'nav.selfStudyGuide': 'Self-Study Guide',
    'nav.level': 'Level',
    'nav.downloadPdf': 'Download PDF',
    'nav.complete': 'Complete',
    'nav.page': 'Page',
    'nav.of': 'of',
    'nav.mainMenu': 'Main Menu',
    'nav.libraryHome': 'Library Home',
    'nav.returnToLibrary': 'Return to Library',
    'nav.guidesResources': 'Guides & Resources',
    'nav.tableOfContents': 'Table of Contents',
    'nav.studentSelfStudyGuide': "Student's Self-Study Guide",
    'nav.reflectionPractice': 'Reflection, Practice & Personal Growth',
    'nav.interactiveEbookSeries': 'Interactive E-Book Series • Student Module',
    'nav.professionalTeacherGuide': 'Professional Teacher Guide',
    'nav.educationalSupport': 'Educational Implementation Support',
    'nav.version': 'Version',
    'nav.modularBuild': 'Modular Build',
    'nav.storiesProphetsSeries': 'Stories of the Prophets Series • Interactive Edition',
    'nav.elementary': 'Elementary',
    'nav.intermediate': 'Intermediate',
    'nav.upperIntermediate': 'Upper Intermediate',
    'nav.advanced': 'Advanced',
    'nav.chapter': 'Chapter',
    'nav.quickChallenge': 'Quick Challenge',
    'nav.testUnderstanding': 'Test your understanding of this page.',
    'nav.interactiveChallenge': 'Interactive Challenge',
    'nav.masteryAchieved': 'Mastery Achieved!',
    'nav.masteryDesc': 'You have completed all the challenges for the Story of Adam (AS).',
    'nav.completed': 'Completed',
    'nav.startExercise': 'Start Exercise',
    'nav.correctWellDone': 'Correct! Well done.',
    'nav.incorrect': 'Incorrect.',
    'nav.challengeComplete': 'Challenge Complete!',
    'nav.journeySummary': 'Your journey through the Story of Adam (AS) is summarized below:',
    'nav.question': 'Question',
    'nav.correct': 'Correct',
    'nav.finishContinue': 'Finish & Continue',
    'nav.notQuite': 'Not quite...',
    'nav.explanation': 'Explanation',
    'nav.continue': 'Continue',
    'nav.true': 'TRUE',
    'nav.false': 'FALSE',
    'nav.matchingInstructions': 'Match the concepts on the left with their meanings on the right.',
    'nav.matchedThem': "I've matched them!",
    'nav.tapToReveal': 'Tap to reveal',
    'nav.individualMode': 'Individual Mode',
    'nav.pairMode': 'Pair Mode',
    'nav.classMode': 'Class Mode',
    'nav.reflectedOnThese': "I've reflected on these",
    'nav.sequencingInstructions': 'Click the events in the correct order',
    'nav.checkOrder': 'Check Order',
    'nav.selectAllEvents': 'Select all events',
    'nav.check': 'Check Answer',
    'nav.availableItems': 'Available Items (Click to select)',
    'nav.allItemsAssigned': 'All items assigned',
    'nav.reset': 'Reset',
    'nav.assignAllItems': 'Assign all items',
    'nav.submitCategories': 'Submit Categories',
    'nav.step': 'Step',
    'nav.journey': 'Journey',
    'nav.nextQuestion': 'Next Question',
    'nav.seeResults': 'See Results',
    'nav.hideHint': 'Hide Hint',
    'nav.needHint': 'Need a Hint?',
    'nav.hint': 'Hint:',
    'nav.masterGlossary': 'Master Glossary',
    'nav.everyWordLearned': "Every word you've learned in this journey",
    'nav.searchPlaceholder': 'Search for a word or definition...',
    'nav.iKnowThisWord': 'I know this word',
    'nav.needToReview': 'Need to review this word',
    'nav.noWordsFound': 'No words found matching your search.',
    'nav.noWordsCategory': 'No words in this category yet.',
    'nav.glossaryTip': 'Tap ✓ when you know a word, ✗ when you need more practice.',
    'nav.glossaryAmazing': 'Amazing! You know all the words! 🎉',
    'nav.glossaryProgress': 'You know {percent}% of the {total} words so far.',
    'nav.finalChallenge': 'Final Challenge',
    'nav.finalChallengeIntro': "You've reached the end of the journey. Bring the whole story together with a carefully designed final challenge.",
    'nav.startChallenge': 'Start the Challenge',
    'nav.perfectScore': 'Perfect Score!',
    'nav.greatJob': 'Great Job!',
    'nav.keepPracticing': 'Keep Practicing!',
    'nav.tryAgain': 'Try Again',
    'nav.resultsSummary': 'You got {score} out of {total} questions correct.',
    'nav.finishJourney': 'Finish Journey',
    'nav.score': 'Score',
    'nav.all': 'All',
    'nav.known': 'Known',
    'nav.review': 'Review',
    'nav.new': 'New',
    'prophet.adam': 'Prophet Adam',
    'prophet.ibrahim': 'Prophet Abraham',
    'prophet.musa': 'Prophet Moses',
    'prophet.mecca': 'Mecca Before Islam',
    'prophet.yunusEmre': 'Yunus Emre',
    'prophet.adam.desc': 'The story of the first human, knowledge, and the beginning of humanity.',
    'prophet.ibrahim.desc': 'The search for truth, the building of the Kaaba, and unwavering faith.',
    'prophet.musa.desc': 'The journey from the palace to the desert, and the liberation of a people.',
    'prophet.mecca.desc': 'The City and the Age of Ignorance: Mecca before the dawn of Islam.',
    'prophet.yunusEmre.desc': 'The story of a wise Anatolian dervish who taught love, humility, and devotion through simple Turkish poetry.',
    'tg.title': "Teacher's Professional Guide",
    'tg.subtitle': 'Holistic Education Implementation Support',
    'tg.overview': 'Overview',
    'tg.curriculum': 'Curriculum Alignment',
    'tg.approach': 'Teaching Approach',
    'tg.plans': 'Implementation Plans',
    'tg.framework': 'Reading Framework',
    'tg.chapters': 'Chapter Support',
    'tg.management': 'Classroom Management',
    'tg.differentiation': 'Differentiation',
    'tg.assessment': 'Assessment & Rubrics',
    'tg.kinesthetic': 'Kinesthetic Learning',
    'tg.global': 'Global Citizenship',
    'tg.values': 'Values Education',
    'tg.sensitive': 'Sensitive Notes',
    'tg.tips': 'English Tips',
    'tg.home': 'Home Connection',
    'tg.homeConnection': 'Home Connection',
    'tg.glossary': 'Glossary',
    'tg.parentTask': 'Parent Task',
    'tg.resources': 'Extra Resources',
    'tg.checklist': 'Quick Checklist',
    'tg.appendices': 'Appendices',
    'tg.purpose': 'Purpose of the Book',
    'tg.targetLearners': 'Target Learners',
    'tg.mainFocus': 'Main Learning Focus',
    'tg.fluency': 'Fluency',
    'tg.fluencyDesc': 'Reading and listening fluency.',
    'tg.vocabulary': 'Vocabulary',
    'tg.vocabularyDesc': 'Basic story comprehension and core thematic vocabulary.',
    'tg.character': 'Character',
    'tg.characterDesc': 'Values and character education.',
    'tg.holisticAlignment': 'Holistic Education Alignment',
    'tg.holisticDesc': 'Focusing on the holistic development of the student.',
    'tg.listeningViewing': 'Listening & Viewing',
    'tg.listeningViewingDesc': 'Students follow guided audio and visual cues.',
    'tg.readingComprehension': 'Reading Comprehension',
    'tg.readingComprehensionDesc': 'Students move from literal understanding to simple inference.',
    'tg.spokenInteraction': 'Spoken Interaction',
    'tg.spokenInteractionDesc': 'Students answer short questions, compare ideas, and retell events.',
    'tg.vocabularyDev': 'Vocabulary Development',
    'tg.vocabularyDevDesc': 'Students meet useful thematic words in context and recycle them during discussion.',
    'tg.valuesEducation': 'Values Education',
    'tg.valuesEducationDesc': 'Humility, sincerity, responsibility, patience, regret, self-control, peaceful behavior.',
    'tg.sel': 'Social-Emotional Learning',
    'tg.selDesc': 'Identifying feelings, discussing consequences, making better choices.',
    'tg.principles': 'Teaching Principles',
    'tg.approachDesc': 'The teaching approach should remain simple, supportive, interactive, and appropriate for A2 learners.',
    'tg.corePrinciples': 'Core Principles',
    'tg.classroomSequence': 'Classroom Sequence',
    'tg.teacherRole': 'Teacher Role',
    'tg.interaction': 'Interaction',
    'tg.languageUse': 'Language Use',
    'tg.bdaFramework': 'Before / During / After Framework',
    'tg.beforeReading': 'Before Reading',
    'tg.duringReading': 'During Reading',
    'tg.afterReading': 'After Reading',
    'tg.chapterSupport': 'Chapter-by-Chapter Support',
    'tg.pedagogicalModule': 'Pedagogical Module',
    'tg.learningObjectives': 'Learning Objectives',
    'tg.pedagogyApproach': 'Pedagogy & Approach',
    'tg.grammarFocus': 'Grammar Focus',
    'tg.pronunciationFocus': 'Pronunciation Focus',
    'tg.lessonFlow': 'Lesson Flow (Step-by-Step)',
    'tg.assessmentTools': 'Assessment Tools',
    'tg.sampleRubric': 'Sample Rubric',
    'tg.exitTicketQuestions': 'Exit Ticket Questions',
    'tg.discussionPoints': 'Discussion Points',
    'tg.fastFinishers': 'Fast Finishers',
    'tg.strugglingLearners': 'Struggling Learners',
    'tg.appTips': 'Interactive App Tips',
    'tg.wholeClassMode': 'Whole-Class Mode',
    'tg.wholeClassModeDesc': 'Teacher projects the story and controls the pace.',
    'tg.pairWorkMode': 'Pair Work Mode',
    'tg.pairWorkModeDesc': 'One student reads, one student supports with hotspots or explanation.',
    'tg.quizMode': 'Quiz Mode',
    'tg.quizModeDesc': 'Use teams for motivation, not pressure.',
    'tg.exitTicketMode': 'Exit Ticket Mode',
    'tg.exitTicketModeDesc': 'Close each lesson with a short written check.',
    'tg.practicalNotes': 'Practical Notes',
    'tg.practicalNote1': 'Keep transitions quick.',
    'tg.practicalNote2': 'Do not read too much without stopping.',
    'tg.practicalNote3': 'Let weaker students rehearse in pairs before public speaking.',
    'tg.practicalNote4': 'Keep hotspot use purposeful.',
    'tg.diffStrategies': 'Differentiation Strategies',
    'tg.forSupport': 'For Support',
    'tg.forSupport1': 'Use visuals first.',
    'tg.forSupport2': 'Ask yes/no or either/or questions.',
    'tg.forSupport3': 'Allow short L1 support for abstract ideas.',
    'tg.forSupport4': 'Repeat key sentences together.',
    'tg.forSupport5': 'Use sentence starters.',
    'tg.forExtension': 'For Extension',
    'tg.forExtension1': 'Ask for diary entries.',
    'tg.forExtension2': 'Ask “why” questions with sentence frames.',
    'tg.forExtension3': 'Let students create a values poster.',
    'tg.forExtension4': 'Ask students to give advice in English.',
    'tg.forMixedAbility': 'For Mixed Ability',
    'tg.forMixedAbility1': 'Use peer support.',
    'tg.forMixedAbility2': 'Give optional challenge tasks, not compulsory extra pressure.',
    'tg.forMixedAbility3': 'Keep core success simple and reachable for everyone.',
    'tg.assessmentEvidence': 'Assessment & Learning Evidence',
    'tg.lookFor': 'What to Look For',
    'tg.lookFor1': 'Can the student follow the main story line?',
    'tg.lookFor2': 'Can the student use a few target words correctly?',
    'tg.lookFor3': 'Can the student answer simple questions in English?',
    'tg.lookFor4': 'Can the student connect the lesson to a value or personal idea?',
    'tg.masterRubric': 'Master Rubric (A2 Level)',
    'tg.criterion': 'Criterion',
    'tg.excellent': 'Excellent (5)',
    'tg.good': 'Good (3)',
    'tg.developing': 'Developing (1)',
    'tg.kinestheticActivities': 'Kinesthetic Learning Activities',
    'tg.kinestheticDesc': 'Use movement briefly and purposefully. These activities should support language and recall, not replace reading.',
    'tg.statueGallery': 'Statue Gallery',
    'tg.vocabularyHop': 'Vocabulary Hop',
    'tg.storyWalk': 'Story Walk Timeline',
    'tg.emotionMirroring': 'Emotion Mirroring',
    'tg.mimeAction': 'Mime the Action',
    'tg.totalPhysicalResponse': 'Total Physical Response (TPR)',
    'tg.totalPhysicalResponseDesc': 'Use physical movement to reinforce language and concepts.',
    'tg.storyActing': 'Story Acting',
    'tg.storyActingDesc': 'Students act out scenes from the story to demonstrate understanding.',
    'tg.interactiveHotspots': 'Interactive Hotspots',
    'tg.interactiveHotspotsDesc': 'Use the digital hotspots to explore vocabulary and deeper meanings.',
    'tg.classroomGames': 'Classroom Games',
    'tg.classroomGamesDesc': 'Engage students with games that recycle story language.',
    'tg.storyWalkTimelineDesc': 'Create a visual timeline of events in the classroom.',
    'tg.globalCitizenship': 'Global Citizenship & Values Bridge',
    'tg.coreGlobalValues': 'Core Global Values',
    'tg.keyThemes': 'Key Themes',
    'tg.humanEquality': 'Human Equality',
    'tg.humanEqualityDesc': 'Discussing how we are all related and share a common origin.',
    'tg.respectDifferences': 'Respect Across Differences',
    'tg.respectDifferencesDesc': 'Valuing diversity in skin color, language, and background.',
    'tg.natureResponsibility': 'Responsibility toward nature:',
    'tg.natureResponsibilityDesc': 'Being a caretaker (Khalifah) of the Earth.',
    'tg.peacefulResolution': 'Peaceful conflict resolution:',
    'tg.peacefulResolutionDesc': 'Learning from the story of Habil and Qabil.',
    'tg.rejectingSuperiority': 'Rejecting superiority:',
    'tg.rejectingSuperiorityDesc': 'Understanding the danger of arrogance (Iblis).',
    'tg.actionPoints': 'Action Points',
    'tg.globalAction1': 'If all people come from one human beginning, how should we treat each other?',
    'tg.globalAction2': 'Why is it wrong to think one group is better than another?',
    'tg.globalAction3': 'How can we solve problems peacefully?',
    'tg.suggestedQuestions': 'Suggested Questions',
    'tg.extraMaterials': 'Extra Materials & Resources',
    'tg.printableWorksheets': 'Printable Worksheet Drafts',
    'tg.externalLinks': 'Recommended External Links',
    'tg.valuesCharacter': 'Values & Character Education',
    'tg.keyValues': 'Key Values',
    'tg.humility': 'Humility',
    'tg.humilityQ': 'Why is humility better than arrogance?',
    'tg.sincerity': 'Sincerity',
    'tg.sincerityQ': 'Why is real goodness important?',
    'tg.responsibility': 'Responsibility',
    'tg.responsibilityQ': 'What does it mean to care for the world?',
    'tg.honesty': 'Honesty',
    'tg.honestyQ': 'Why is truth important?',
    'tg.regret': 'Regret',
    'tg.regretQ': 'Why is admitting a mistake a strength?',
    'tg.peace': 'Peace & Self-Control',
    'tg.peaceQ': 'How can we stop anger before it grows?',
    'tg.jealousyQ': 'How can we trust Allah during difficult tests?',
    'tg.sensitiveGuidance': 'Sensitive Pedagogical Guidance',
    'tg.keyGuidance': 'Key Guidance',
    'tg.teacherTipsEnglish': 'Teacher Tips for English Use',
    'tg.simpleClassroomEnglish': 'Simple Classroom English',
    'tg.supportMeaning': 'Support Meaning',
    'tg.praiseEffort': 'Praise Effort',
    'tg.consistency': 'Consistency',
    'tg.recycle': 'Recycle',
    'tg.l1Use': 'L1 Use',
    'tg.production': 'Production',
    'tg.usefulLanguage': 'Useful Classroom Language',
    'tg.familyPrompt': 'Family Discussion Prompt',
    'tg.sampleHomeTasks': 'Sample Home Tasks',
    'tg.quickChecklist': 'Quick Use Checklist',
    'tg.beforeClass': 'Before Class',
    'tg.duringClass': 'During Class',
    'tg.afterClass': 'After Class',
    'tg.readyAppendices': 'Ready-to-Use Appendices',
    'tg.sampleExitTicket': 'Sample Exit Ticket',
    'tg.preTeach': 'Pre-teach only a few key words. Use visuals first, then audio, then text. Move from “What happened?” to “Why did it happen?”',
    'tg.sequence': '1. See it (visuals). 2. Hear it (audio). 3. Read it (text). 4. Say it (answer/retell). 5. Connect it (link to life).',
    'tg.guideNotLecturer': 'Act as a guide, not a lecturer. Help students notice, understand, speak, and reflect.',
    'tg.pairTalk': 'Use pair talk before whole-class answers. End each lesson with a short real-life bridge.',
    'tg.clearTeacherTalk': 'Keep teacher talk clear and short. Repeat important language in natural ways.',
    'ssg.whoIsThisFor': '1. Who is this for?',
    'ssg.whoIsThisForDesc': 'This guide is for A2 English learners (Grades 6-8). It helps you understand the story and learn new words easily.',
    'ssg.learnerType1': 'English students',
    'ssg.learnerType2': 'Learners studying alone or with a teacher',
    'ssg.whatInBook': '2. What is in the book?',
    'ssg.whatInBookDesc': 'This is an interactive storybook about Prophet Adam. It has more than just text!',
    'ssg.content1': 'Stories to read and listen',
    'ssg.content2': 'Pictures and word help',
    'ssg.content3': 'Games and quizzes',
    'ssg.content4': 'Reflection questions',
    'ssg.howToUse': '3. How to use the book',
    'ssg.howToUseDesc': 'Follow these 4 simple steps for every page:',
    'ssg.step1': 'Step 1: Look at the picture and title.',
    'ssg.step2': 'Step 2: Listen to the audio first.',
    'ssg.step3': 'Step 3: Read the text slowly.',
    'ssg.step4': 'Step 4: Do the activities and check the notes.',
    'ssg.routine': '4. Your Study Routine',
    'ssg.routineDesc': "You don't need hours. Small steps are better!",
    'ssg.routine1': 'Short (10m): Listen, read, and do 1 activity.',
    'ssg.routine2': 'Normal (20m): Listen, read, learn 5 words, do all activities.',
    'ssg.routine3': 'Long (40m): Full study, write a summary, review old words.',
    'ssg.readingTips': '5. Reading Tips',
    'ssg.readingTipsDesc': 'How to read like a pro:',
    'ssg.readingTip1': 'Before: Look at the picture and guess the story.',
    'ssg.readingTip2': 'While: Read small parts. Don\'t rush!',
    'ssg.readingTip3': 'After: Say 1 sentence about what happened.',
    'ssg.learningWords': '6. Learning New Words',
    'ssg.learningWordsDesc': 'Don\'t try to learn everything. Choose 3-5 words per page.',
    'ssg.learningWord1': 'Notice: Find a new word.',
    'ssg.learningWord2': 'Understand: Click it to see the meaning.',
    'ssg.learningWord3': 'Write: Put it in your notebook with an example.',
    'ssg.learningWord4': 'Review: Look at it again tomorrow.',
    'ssg.listeningSpeaking': '7. Listening & Speaking',
    'ssg.listeningSpeakingDesc': 'Use your ears and your voice!',
    'ssg.listeningSpeaking1': 'Listen 3 times: General idea -> With text -> Repeat sentences.',
    'ssg.listeningSpeaking2': 'Speak aloud: Read sentences after the audio to practice sound.',
    'ssg.writingPractice': '8. Writing Practice',
    'ssg.writingPracticeDesc': 'Writing helps you remember.',
    'ssg.writingPractice1': 'Write 3 new words.',
    'ssg.writingPractice2': 'Write 1 lesson you learned.',
    'ssg.writingPractice3': 'Write a very short summary (2 sentences).',
    'ssg.whenHard': '9. When it feels hard',
    'ssg.whenHardDesc': 'It\'s okay to make mistakes! That is how we learn.',
    'ssg.whenHard1': 'Take a short break.',
    'ssg.whenHard2': 'Listen again. It gets easier!',
    'ssg.whenHard3': 'Ask a teacher or friend for help.',
    'ssg.chapterSupport': '10. Chapter Support',
    'ssg.chapterSupportDesc': 'Quick tips for your journey:',
    'ssg.chapterSupport1': 'Early chapters: Focus on monotheism, searching for truth, and rejecting idols.',
    'ssg.chapterSupport2': 'Middle chapters: Focus on courage, debate, trust in Allah, and trials.',
    'ssg.chapterSupport3': 'Later chapters: Focus on family, sacrifice, and themes of Zamzam and the Kaaba.',
    'ssg.welcome': 'Welcome',
    'ex.perfect': 'Perfect!',
    'ex.amazing': 'Amazing!',
    'ex.goodJob': 'Good job!',
    'ex.keepGoing': 'Keep going!',
    'ex.streak': 'streak!',
    'ex.pts': 'pts',
    'ex.true': 'True',
    'ex.false': 'False',
    'ex.tfChallenge': 'True / False Challenge',
    'ex.seeResults': 'See Results',
    'ex.tryAgain': 'Try Again',
    'ex.correct': 'Correct!',
    'ex.notQuite': 'Not quite!',
    'ex.explanation': 'Explanation',
    'ex.scoreSummary': 'You got {correct} out of {total} correct ({percent}%).',
    'ex.feedbackPanel': 'Feedback Panel',
    'ex.feedbackHint': 'Answer all questions, then tap the {info} icon to see detailed feedback.',
    'ex.perfectOrder': 'Perfect order!',
    'ex.allEventsCorrect': 'All {total} events in the correct sequence.',
    'ex.firstTry': 'First try — excellent!',
    'ex.secondTry': 'Got it on the second try!',
    'ex.completedIn': 'Completed in {attempts} attempts.',
    'ex.itemsOutOfPlace': '{count} items out of place',
    'ex.itemOutOfPlace': '1 item out of place',
    'ex.rearrangeHint': 'Items marked with ✗ show their correct position. Rearrange and try again!',
    'ex.showAnswer': 'Show Answer',
    'ex.retry': 'Retry',
    'ex.dragHint': 'Drag the items using ≡ to arrange them in the correct order, then tap Verify.',
    'ex.sequenceChallenge': 'Sequence Challenge',
    'ex.arrangeOrder': 'Arrange the events in the correct order',
    'ex.attempt': 'Attempt',
    'ex.verifySequence': 'Verify Sequence',
    'ex.allWordsMatched': 'All {total} words matched!',
    'ex.bestStreak': 'Best streak: {count} in a row — excellent focus!',
    'ex.greatWork': 'Great work completing the exercise!',
    'ex.means': 'means',
    'ex.doesNotMean': 'does not mean',
    'ex.keepTrying': 'Keep trying!',
    'ex.selectWordHint': 'Select a word, then select its meaning to make a match.',
    'ex.allMatchedJob': 'All words matched — great job!',
    'ex.tapToBegin': 'Tap a word or a meaning to begin',
    'ex.wordSelectedHint': '"{word}" selected — now pick its meaning',
    'ex.meaningSelectedHint': 'Meaning selected — now pick the matching word',
    'ex.words': 'Words',
    'ex.meanings': 'Meanings',
    'ex.type.true-false': 'True or False',
    'ex.type.multiple-choice': 'Multiple Choice',
    'ex.type.sequencing': 'Sequencing',
    'ex.type.vocabulary-match': 'Vocabulary Match',
    'ex.type.quiz': 'Quiz',
    'ex.type.quiz-game': 'Quiz Game',
    'ex.type.game': 'Game',
    'ex.type.exercises': 'Exercises',
    'ex.type.drag-drop': 'Drag and Drop',
    'ex.type.reflection': 'Reflection',
    'ex.type.tap-reveal': 'Tap to Reveal',
    'nav.keyWordFallback': 'A key word in this story.',
    'tg.exitTicket1': 'One thing I learned today: ________',
    'tg.exitTicket2': 'One word I want to remember: ______',
    'tg.exitTicket3': 'One question I still have: ________',
    'tg.miniProjectIdea': 'Mini-Project Idea',
    'tg.miniProjectDesc': '"Create a 3-panel values comic showing a good choice, a mistake, and a better response. Add short English captions."',
    'tg.reflectiveWritingPrompt': 'Reflective Writing Prompt',
    'tg.reflectiveWritingDesc': '“People make mistakes, but they can learn and return to the right way. Write about a time you learned from a mistake.”',
    'tg.creationMap': 'The Creation Map',
    'tg.creationMapType': 'Sequencing & Drawing',
    'tg.characterTraitsChart': 'Character Traits Chart',
    'tg.characterTraitsChartType': 'Adjectives & Evidence',
    'tg.regretLetter': 'The Regret Letter',
    'tg.regretLetterType': 'Creative Writing Prompt',
    'tg.vocabularyCrossword': 'Vocabulary Crossword',
    'tg.vocabularyCrosswordType': 'Chapter 1-5 Review',
    'tg.interactiveWordList': 'Interactive CEFR A2 Word List',
    'tg.guidance1': 'Present Adam’s mistake as a learning moment.',
    'tg.guidance2': 'Handle the death of Habil calmly and carefully.',
    'tg.guidance3': 'Present Iblis as a warning example of arrogance.',
    'tg.guidance4': 'Keep language age-appropriate and non-graphic.',
    'tg.guidance5': 'Focus on lesson, consequence, and better choices.',
    'tg.simpleEnglishDesc': 'Keep classroom English simple and repeatable.',
    'tg.supportMeaningDesc': 'Support meaning with visuals, gesture, repetition, and sentence frames.',
    'tg.praiseEffortDesc': 'Praise effort specifically.',
    'tg.consistencyDesc': 'Keep instructions short and consistent.',
    'tg.recycleDesc': 'Recycle target words across lessons.',
    'tg.l1UseDesc': 'Use native language only briefly when truly needed for abstract meaning.',
    'tg.productionDesc': 'Return student production to English whenever possible.',
    'tg.classroomLang1': '“Listen and follow.”',
    'tg.classroomLang2': '“Work with your partner.”',
    'tg.classroomLang3': '“Say one sentence.”',
    'tg.classroomLang4': '“What happened first?”',
    'tg.classroomLang5': '“Why do you think that?”',
    'tg.classroomLang6': '“Use the new word in your answer.”',
    'tg.homeAction1': 'Ask students to discuss one lesson with family.',
    'tg.homeAction2': 'Encourage home listening practice.',
    'tg.homeAction3': 'Give short reflection tasks that do not create heavy homework.',
    'tg.homeAction4': 'Use homework to recycle language, not overload learners.',
    'tg.informativeNarratives': 'The texts here are informative narratives.',
    'tg.parentTask1': 'Listen again and repeat 5 lines.',
    'tg.parentTask2': 'Ask one family discussion question.',
    'tg.parentTask3': 'Write 2–3 simple sentences using new vocabulary.',
    'tg.checklistBefore1': 'Check screen and audio.',
    'tg.checklistBefore2': 'Open the correct page.',
    'tg.checklistBefore3': 'Prepare 4–6 target words.',
    'tg.checklistBefore4': 'Decide where you will pause.',
    'tg.checklistDuring1': 'Keep pace manageable.',
    'tg.checklistDuring2': 'Pause after short chunks.',
    'tg.checklistDuring3': 'Use pair talk before responses.',
    'tg.checklistDuring4': 'Check understanding often.',
    'tg.checklistAfter1': 'Collect exit tickets.',
    'tg.checklistAfter2': 'Note difficult vocabulary.',
    'tg.checklistAfter3': 'Record revision needs.',
    'tg.checklistAfter4': 'Adjust next lesson.',
    'tg.sentence1': '“Adam was created from …”',
    'tg.sentence2': '“Knowledge is important because …”',
    'tg.sentence3': '“Adam was more … than …”',
    'tg.sentence4': '“First … Then … After that …”',
    'tg.sentence5': '“The lesson of this story is …”',
    'ssg.sectionOf': 'Section {section} of {total} • Student Self-Study Guide',
    'ssg.welcomeExplorer': 'Welcome, Explorer!',
    'ssg.welcomeDesc': 'This book is your journey through history and wisdom. You are not just reading; you are learning how to be a better person through the story of the first human.',
    'ssg.yourMission': 'Your Mission',
    'ssg.missionDesc': '"Read carefully, listen closely, and think deeply. Every page has a lesson for your heart and your mind."',
    'ssg.fullGuide': 'Full Guide',
    'bg.rollToStart': 'Roll the dice to start your journey!',
    'bg.journeyComplete': 'Journey Complete',
    'bg.rollDice': 'Roll Dice',
    'bg.cell.1.title': 'Start',
    'bg.cell.1.info': 'The journey begins.',
    'bg.cell.2.title': 'Clay',
    'bg.cell.2.info': 'Man was created from humble clay.',
    'bg.cell.3.title': 'Names',
    'bg.cell.3.info': 'Knowledge is a gift from Allah.',
    'bg.cell.4.title': 'Angels',
    'bg.cell.4.info': 'They prostrated out of obedience.',
    'bg.cell.5.title': 'Iblis',
    'bg.cell.5.info': 'arrogance leads to downfall.',
    'bg.cell.6.title': 'Garden',
    'bg.cell.6.info': 'A place of peace and beauty.',
    'bg.cell.7.title': 'Test',
    'bg.cell.7.info': 'Every blessing comes with a test.',
    'bg.cell.8.title': 'Tree',
    'bg.cell.8.info': 'Boundaries are for our protection.',
    'bg.cell.9.title': 'Whisper',
    'bg.cell.9.info': "Be wary of Satan's deception.",
    'bg.cell.10.title': 'Mistake',
    'bg.cell.10.info': 'Humans are prone to error.',
    'bg.cell.11.title': 'Repent',
    'bg.cell.11.info': 'Allah is the Most Merciful.',
    'bg.cell.12.title': 'Earth',
    'bg.cell.12.info': 'A new beginning as vicegerents.',
  },
  ar: {
    'nav.home': 'الرَّئِيسِيَّة',
    'home.platformPositioning': 'مكتبة تفاعلية للغات والقيم والأخلاق',
    'home.heroTitle': 'تعلم اللغات عبر القصص المقدسة والتاريخ والتراث الحضاري',
    'home.heroSubtitle': 'اكتشف كتباً تفاعلية باللغتين الإنجليزية والعربية مصممة للطلاب والمعلمين والتعليم القائم على القيم الأخلاقية.',
    'home.exploreLibrary': 'تصفح المكتبة',
    'home.forTeachers': 'للمعلمين والموجهين',
    'home.statStories': '٥ قصص كبرى',
    'home.statBooks': '١٥ كتاباً متدرجاً',
    'home.statLevels': 'المستويات A2–B2',
    'home.statLanguages': 'الإنجليزية والعربية',
    'home.statGuides': 'أدلة للمعلم والدراسة الذاتية',
    'home.featInteractiveTitle': 'قراءة تفاعلية نشطة',
    'home.featInteractiveDesc': 'اقرأ محتوى غني بمفردات توضيحية، تشغيل صوتي حي، وتتبع تلقائي لمكتسباتك.',
    'home.featLevelsTitle': 'تعلم متدرج المستويات',
    'home.featLevelsDesc': 'تقدم بسلاسة بين مستويات الإطار الأوروبي المشترك (CEFR) من A2 إلى B2 المخصصة للتطور اللغوي الحديث.',
    'home.featValuesTitle': 'التربية على مبادئ القيم',
    'home.featValuesDesc': 'الكرامة الإنسانية، الحق، العدالة الاجتماعية، والصدق والوفاء مغروسة في تصميمنا السردي المبتكر.',
    'home.featTeachersTitle': 'جاهزية كاملة للفصول',
    'home.featTeachersDesc': 'تضم مشغلات فورية، خطط دروس معيارية، قوالب تقييم، وأنشطة تواصل منزلية وعائلية.',
    'home.collection1': 'قصص الأنبياء عليهم السلام',
    'home.collection1Desc': 'استكشف سير الأنبياء من خلال فصول تفاعلية، ومفردات، واستماع، وتمارين، وتأملات أخلاقية سامية.',
    'home.collection1Tag': 'السيرة النبوية',
    'home.collection2': 'التاريخ والحضارة الإسلامية',
    'home.collection2Desc': 'اكتشف الحواضر والمجتمعات والمنعطفات التاريخية التي شكلت العالم الذي بزغ فيه نور الإسلام.',
    'home.collection2Tag': 'التاريخ والحضارة الإسلامية',
    'home.collection3': 'أعلام التراث التركي الإسلامي',
    'home.collection3Desc': 'تعرف على كبار الشعراء والعلماء والدراويش والحكماء الذين شكلوا الفكر والأخلاق واللغة في التراث التركي الإسلامي.',
    'home.collection3Tag': 'التراث التركي الإسلامي',
    'home.explore': 'استكشف المجموعة',
    'home.collectionStories': 'قصص',
    'home.selectToBegin': 'اختر قصة من المجموعة لتحديد المستوى والبدء.',
    'nav.homeTitle': 'قِصَصُ الأَنْبِيَاء',
    'nav.homeSubtitle': 'رِحْلَةٌ تَفَاعُلِيَّةٌ عَبْرَ الإِيمَانِ وَالْحِكْمَةِ وَالتَّارِيخ.',
    'nav.back': 'السَّابِق',
    'nav.next': 'التَّالِي',
    'nav.finish': 'إِنْهَاء',
    'nav.begin': 'ابْدَأِ الرِّحْلَة',
    'nav.selectStory': 'اخْتَرْ قِصَّة',
    'nav.chooseLevel': 'اخْتَرْ مُسْتَوَاك',
    'nav.comingSoon': 'قَرِيباً',
    'nav.meaning': 'الْمَعْنَى',
    'nav.teacherGuide': 'دَلِيلُ الْمُعَلِّم',
    'nav.selfStudyGuide': 'دَلِيلُ الدِّرَاسَةِ الذَّاتِيَّة',
    'nav.level': 'الْمُسْتَوَى',
    'nav.downloadPdf': 'تَحْمِيل PDF',
    'nav.complete': 'مُكْتَمَل',
    'nav.page': 'صَفْحَة',
    'nav.of': 'مِن',
    'nav.mainMenu': 'الْقَائِمَةُ الرَّئِيسِيَّة',
    'nav.libraryHome': 'مَكْتَبَةُ الْقِصَص',
    'nav.returnToLibrary': 'الْعَوْدَةُ إِلَى الْمَكْتَبَة',
    'nav.guidesResources': 'الأَدِلَّةُ وَالْمَوَارِد',
    'nav.tableOfContents': 'فِهْرِسُ الْمُحْتَوَيَات',
    'nav.studentSelfStudyGuide': 'دَلِيلُ الدِّرَاسَةِ الذَّاتِيَّةِ لِلطَّالِب',
    'nav.reflectionPractice': 'التَّفْكِيرُ وَالْمُمَارَسَةُ وَالنُّمُوُّ الشَّخْصِي',
    'nav.interactiveEbookSeries': 'سِلْسِلَةُ الْكُتُبِ الإِلِكْتُرُونِيَّةِ التَّفَاعُلِيَّة • وَحْدَةُ الطَّالِب',
    'nav.professionalTeacherGuide': 'دَلِيلُ الْمُعَلِّمِ الْمِهْنِي',
    'nav.educationalSupport': 'دَعْمُ تَنْفِيذِ التَّعْلِيمِ الشَّامِل',
    'nav.version': 'الإِصْدَار',
    'nav.modularBuild': 'بِنَاءٌ مِعْيَارِي',
    'nav.storiesProphetsSeries': 'سِلْسِلَةُ قِصَصِ الأَنْبِيَاء • النُّسْخَةُ التَّفَاعُلِيَّة',
    'nav.elementary': 'ابْتِدَائِي',
    'nav.intermediate': 'مُتَوَسِّط',
    'nav.upperIntermediate': 'فَوْقَ الْمُتَوَسِّط',
    'nav.advanced': 'مُتَقَدِّم',
    'nav.chapter': 'الْفَصْل',
    'nav.quickChallenge': 'تَحَدٍّ سَرِيع',
    'nav.testUnderstanding': 'اخْتَبِرْ فَهْمَكَ لِهَذِهِ الصَّفْحَة.',
    'nav.interactiveChallenge': 'تَحَدٍّ تَفَاعُلِي',
    'nav.masteryAchieved': 'تَمَّ تَحْقِيقُ الإِتْقَان!',
    'nav.masteryDesc': 'لَقَدْ أَكْمَلْتَ جَمِيعَ التَّحَدِّيَاتِ لِقِصَّةِ آدَم (عَلَيْهِ السَّلَام).',
    'nav.completed': 'مُكْتَمَل',
    'nav.startExercise': 'ابْدَأِ التَّمْرِين',
    'nav.correctWellDone': 'صَحِيح! أَحْسَنْت.',
    'nav.incorrect': 'غَيْرُ صَحِيح.',
    'nav.challengeComplete': 'اكْتَمَلَ التَّحَدِّي!',
    'nav.journeySummary': 'مُلَخَّصُ رِحْلَتِكَ عَبْرَ قِصَّةِ آدَم (ع) أَدْنَاه:',
    'nav.question': 'السُّؤَال',
    'nav.correct': 'صَحِيح',
    'nav.finishContinue': 'إِنْهَاءٌ وَمُتَابَعَة',
    'nav.notQuite': 'لَيْسَ تَمَاماً...',
    'nav.explanation': 'التَّفْسِير',
    'nav.continue': 'مُتَابَعَة',
    'nav.true': 'صَحِيح',
    'nav.false': 'خَطَأ',
    'nav.matchingInstructions': 'طَابِقِ الْمَفَاهِيمَ عَلَى الْيَمِينِ مَعَ مَعَانِيهَا عَلَى الْيَسَار.',
    'nav.matchedThem': 'لَقَدْ طَابَقْتَهَا!',
    'nav.tapToReveal': 'انْقُرْ لِلْكَشْف',
    'nav.individualMode': 'وَضْعٌ فَرْدِي',
    'nav.pairMode': 'وَضْعٌ ثُنَائِي',
    'nav.classMode': 'وَضْعٌ جَمَاعِي',
    'nav.reflectedOnThese': 'لَقَدْ فَكَّرْتَ فِي هَذِه',
    'nav.sequencingInstructions': 'انْقُرْ عَلَى الأَحْدَاثِ بِالتَّرْتِيبِ الصَّحِيح',
    'nav.checkOrder': 'تَحَقَّقْ مِنَ التَّرْتِيب',
    'nav.selectAllEvents': 'اخْتَرْ جَمِيعَ الأَحْدَاث',
    'nav.check': 'تَحَقَّقْ مِنَ الإِجَابَة',
    'nav.availableItems': 'الْعَنَاصِرُ الْمُتَاحَة (انْقُرْ لِلاخْتِيَار)',
    'nav.allItemsAssigned': 'تَمَّ تَعْيِينُ جَمِيعِ الْعَنَاصِر',
    'nav.reset': 'إِعَادَةُ تَعْيِين',
    'nav.assignAllItems': 'عَيِّنْ جَمِيعَ الْعَنَاصِر',
    'nav.submitCategories': 'إِرْسَالُ الْفِئَات',
    'nav.step': 'الْخُطْوَة',
    'nav.journey': 'الرِّحْلَة',
    'nav.nextQuestion': 'السُّؤَالُ التَّالِي',
    'nav.seeResults': 'رُؤْيَةُ النَّتَائِج',
    'nav.hideHint': 'إِخْفَاءُ التَّلْمِيح',
    'nav.needHint': 'هَلْ تَحْتَاجُ إِلَى تَلْمِيح؟',
    'nav.hint': 'تَلْمِيح:',
    'nav.masterGlossary': 'مَسْرَدُ الْمُصْطَلَحَاتِ الشَّامِل',
    'nav.everyWordLearned': 'كُلُّ كَلِمَةٍ تَعَلَّمْتَهَا فِي هَذِهِ الرِّحْلَة',
    'nav.searchPlaceholder': 'ابْحَثْ عَنْ كَلِمَةٍ أَوْ تَعْرِيف...',
    'nav.iKnowThisWord': 'أَعْرِفُ هَذِهِ الْكَلِمَة',
    'nav.needToReview': 'أَحْتَاجُ لِمُرَاجَعَةِ هَذِهِ الْكَلِمَة',
    'nav.noWordsFound': 'لَمْ يَتِمَّ الْعُثُورُ عَلَى كَلِمَاتٍ تُطَابِقُ بَحْثَك.',
    'nav.noWordsCategory': 'لَا تُوجَدُ كَلِمَاتٌ فِي هَذِهِ الْفِئَةِ بَعْد.',
    'nav.glossaryTip': 'انْقُرْ عَلَى ✓ عِنْدَمَا تَعْرِفُ كَلِمَة، و ✗ عِنْدَمَا تَحْتَاجُ إِلَى مَزِيدٍ مِنَ التَّدْرِيب.',
    'nav.glossaryAmazing': 'مُذْهِل! أَنْتَ تَعْرِفُ كُلَّ الْكَلِمَات! 🎉',
    'nav.glossaryProgress': 'أَنْتَ تَعْرِفُ {percent}% مِنْ أَصْلِ {total} كَلِمَة حَتَّى الآن.',
    'nav.finalChallenge': 'التَّحَدِّي النِّهَائِي',
    'nav.finalChallengeIntro': 'لَقَدْ وَصَلْتَ إِلَى نِهَايَةِ الرِّحْلَة! هَلْ أَنْتَ مُسْتَعِدٌّ لاخْتِبَارِ مَعْرِفَتِكَ بِـ ١٠ أَسْئِلَةٍ عَشْوَائِيَّةٍ مِنَ الْقِصَّة؟',
    'nav.startChallenge': 'ابْدَأِ التَّحَدِّي',
    'nav.perfectScore': 'دَرَجَةٌ كَامِلَة!',
    'nav.greatJob': 'عَمَلٌ رَائِع!',
    'nav.keepPracticing': 'اسْتَمِرَّ فِي التَّدْرِيب!',
    'nav.tryAgain': 'حَاوِلْ مَرَّةً أُخْرَى',
    'nav.resultsSummary': 'لَقَدْ أَجَبْتَ عَلَى {score} مِنْ أَصْلِ {total} بِشَكْلٍ صَحِيح.',
    'nav.finishJourney': 'إِنْهَاءُ الرِّحْلَة',
    'nav.score': 'النَّتِيجَة',
    'nav.all': 'الْكُل',
    'nav.known': 'مَعْرُوف',
    'nav.review': 'مُرَاجَعَة',
    'nav.new': 'جَدِيد',
    'prophet.adam': 'النَّبِيُّ آدَم',
    'prophet.ibrahim': 'النَّبِيُّ إِبْرَاهِيم',
    'prophet.musa': 'النَّبِيُّ مُوسَى',
    'prophet.mecca': 'مكة قبل الإسلام',
    'prophet.yunusEmre': 'يونس إمره',
    'prophet.adam.desc': 'قِصَّةُ أَوَّلِ بَشَر، وَالْعِلْم، وَبِدَايَةِ الإِنْسَانِيَّة.',
    'prophet.ibrahim.desc': 'الْبَحْثُ عَنِ الْحَقِيقَة، وَبِنَاءُ الْكَعْبَة، وَالإِيمَانُ الرَّاسِخ.',
    'prophet.musa.desc': 'الرِّحْلَةُ مِنَ الْقَصْرِ إِلَى الصَّحْرَاء، وَتَحْرِيرُ الشَّعْب.',
    'prophet.mecca.desc': 'المَدِينَة وَعَصْر الجَاهِلِيَّة: مَكَّةُ المُكَرَّمَة قَبْلَ فَجْرِ الإِسْلام.',
    'prophet.yunusEmre.desc': 'قصة الدرويش الأناضولي الحكيم الذي علم الحب والتواضع والولاء من خلال الشعر التركي البسيط.',
    'tg.title': 'دَلِيلُ الْمُعَلِّمِ الْمِهْنِي',
    'tg.subtitle': 'دَعْمُ تَنْفِيذِ التَّعْلِيمِ الشَّامِل',
    'tg.overview': 'نَظْرَةٌ عَامَّة',
    'tg.curriculum': 'مُوَاءَمَةُ الْمَنَاهِج',
    'tg.approach': 'نَهْجُ التَّدْرِيس',
    'tg.plans': 'خُطَطُ التَّنْفِيذ',
    'tg.framework': 'إِطَارُ الْقِرَاءَة',
    'tg.chapters': 'دَعْمُ الْفُصُول',
    'tg.management': 'إِدَارَةُ الْفَصْل',
    'tg.differentiation': 'التَّمَايُز',
    'tg.assessment': 'التَّقْيِيمُ وَمَصَافُّ التَّقْيِيم',
    'tg.kinesthetic': 'التَّعَلُّمُ الْحَرَكِي',
    'tg.global': 'الْمُوَاطَنَةُ الْعَالَمِيَّة',
    'tg.values': 'تَعْلِيمُ الْقِيَم',
    'tg.sensitive': 'مُلَاحَظَاتٌ حَسَّاسَة',
    'tg.tips': 'نَصَائِحُ لِلُّغَةِ الإِنْجِلِيزِيَّة',
    'tg.home': 'التَّوَاصُلُ مَعَ الْمَنْزِل',
    'tg.homeConnection': 'التَّوَاصُلُ مَعَ الْمَنْزِل',
    'tg.glossary': 'مَسْرَدُ الْمُصْطَلَحَات',
    'tg.parentTask': 'مَهَمَّةُ وَلِيِّ الأَمْر',
    'tg.resources': 'مَوَارِدُ إِضَافِيَّة',
    'tg.checklist': 'قَائِمَةٌ مَرْجِعِيَّةٌ سَرِيعَة',
    'tg.appendices': 'الْمَلَاحِق',
    'tg.purpose': 'الْغَرَضُ مِنَ الْكِتَاب',
    'tg.targetLearners': 'الْمُتَعَلِّمُونَ الْمُسْتَهْدَفُون',
    'tg.mainFocus': 'تَرْكِيزُ التَّعَلُّمِ الرَّئِيسِي',
    'tg.fluency': 'الطَّلَاقَة',
    'tg.fluencyDesc': 'طَلَاقَةُ الْقِرَاءَةِ وَالاسْتِمَاع.',
    'tg.vocabulary': 'الْمُفْرَدَات',
    'tg.vocabularyDesc': 'الْفَهْمُ الأَسَاسِيُّ لِلْقِصَّةِ وَالْمُفْرَدَاتُ الْمَوْضُوعِيَّةُ الأَسَاسِيَّة.',
    'tg.character': 'الشَّخْصِيَّة',
    'tg.characterDesc': 'تَعْلِيمُ الْقِيَمِ وَالشَّخْصِيَّة.',
    'tg.holisticAlignment': 'مُوَاءَمَةُ التَّعْلِيمِ الشَّامِل',
    'tg.holisticDesc': 'التَّرْكِيزُ عَلَى التَّطْوِيرِ الشَّامِلِ لِلطَّالِب.',
    'tg.listeningViewing': 'الاسْتِمَاعُ وَالْمُشَاهَدَة',
    'tg.listeningViewingDesc': 'يَتَّبِعُ الطُّلَّابُ الإِشَارَاتِ الصَّوْتِيَّةَ وَالْمَرْئِيَّةَ الْمُوَجَّهَة.',
    'tg.readingComprehension': 'الْفَهْمُ الْقِرَائِي',
    'tg.readingComprehensionDesc': 'يَنْتَقِلُ الطُّلَّابُ مِنَ الْفَهْمِ الْحَرْفِيِّ إِلَى الاسْتِنْتَاجِ الْبَسِيط.',
    'tg.spokenInteraction': 'التَّفَاعُلُ الشَّفَهِي',
    'tg.spokenInteractionDesc': 'يُجِيبُ الطُّلَّابُ عَلَى أَسْئِلَةٍ قَصِيرَة، وَيُقَارِنُونَ الأَفْكَار، وَيُعِيدُونَ سَرْدَ الأَحْدَاث.',
    'tg.vocabularyDev': 'تَطْوِيرُ الْمُفْرَدَات',
    'tg.vocabularyDevDesc': 'يَتَعَرَّفُ الطُّلَّابُ عَلَى كَلِمَاتٍ مَوْضُوعِيَّةٍ مُفِيدَةٍ فِي السِّيَاقِ وَيُعِيدُونَ اسْتِخْدَامَهَا أَثْنَاءَ النِّقَاش.',
    'tg.valuesEducation': 'تَعْلِيمُ الْقِيَم',
    'tg.valuesEducationDesc': 'التَّوَاضُع، الإِخْلَاص، الْمَسْؤُولِيَّة، الصَّبْر، النَّدَم، ضَبْطُ النَّفْس، السُّلُوكُ السِّلْمِي.',
    'tg.sel': 'التَّعَلُّمُ الاجْتِمَاعِيُّ الْعَاطِفِي',
    'tg.selDesc': 'تَحْدِيدُ الْمَشَاعِر، مُنَاقَشَةُ الْعَوَاقِب، اتِّخَاذُ خِيَارَاتٍ أَفْضَل.',
    'tg.principles': 'مَبَادِئُ التَّدْرِيس',
    'tg.approachDesc': 'يَجِبُ أَنْ يَظَلَّ نَهْجُ التَّدْرِيسِ بَسِيطاً، وَدَاعِماً، وَتَفَاعُلِيّاً، وَمُنَاسِباً لِمُتَعَلِّمِي الْمُسْتَوَى A2.',
    'tg.corePrinciples': 'الْمَبَادِئُ الأَسَاسِيَّة',
    'tg.classroomSequence': 'تَسَلْسُلُ الْفَصْلِ الدِّرَاسِي',
    'tg.teacherRole': 'دَوْرُ الْمُعَلِّم',
    'tg.interaction': 'التَّفَاعُل',
    'tg.languageUse': 'اسْتِخْدَامُ اللُّغَة',
    'tg.bdaFramework': 'إِطَارُ (قَبْلَ / أَثْنَاءَ / بَعْدَ)',
    'tg.beforeReading': 'قَبْلَ الْقِرَاءَة',
    'tg.duringReading': 'أَثْنَاءَ الْقِرَاءَة',
    'tg.afterReading': 'بَعْدَ الْقِرَاءَة',
    'tg.chapterSupport': 'دَعْمُ الْفُصُول',
    'tg.pedagogicalModule': 'الْوَحْدَةُ التَّرْبَوِيَّة',
    'tg.learningObjectives': 'أَهْدَافُ التَّعَلُّم',
    'tg.pedagogyApproach': 'الْبِيدَاغُوجِيَا وَالنَّهْج',
    'tg.grammarFocus': 'التَّرْكِيزُ عَلَى الْقَوَاعِد',
    'tg.pronunciationFocus': 'التَّرْكِيزُ عَلَى النُّطْق',
    'tg.lessonFlow': 'تَدَفُّقُ الدَّرْس (خُطْوَةً بِخُطْوَة)',
    'tg.assessmentTools': 'أَدَوَاتُ التَّقْيِيم',
    'tg.sampleRubric': 'عَيِّنَةُ مَصْفُوفَةِ التَّقْيِيم',
    'tg.exitTicketQuestions': 'أَسْئِلَةُ تَذْكِرَةِ الْخُرُوج',
    'tg.discussionPoints': 'نِقَاطُ النِّقَاش',
    'tg.fastFinishers': 'الْمُنْتَهُونَ سَرِيعاً',
    'tg.strugglingLearners': 'الْمُتَعَلِّمُونَ الَّذِينَ يُوَاجِهُونَ صُعُوبَة',
    'tg.appTips': 'نَصَائِحُ التَّطْبِيقِ التَّفَاعُلِي',
    'tg.wholeClassMode': 'وَضْعُ الْفَصْلِ بِأَكْمَلِه',
    'tg.wholeClassModeDesc': 'يَعْرِضُ الْمُعَلِّمُ الْقِصَّةَ وَيَتَحَكَّمُ فِي الْوَتِيرَة.',
    'tg.pairWorkMode': 'وَضْعُ الْعَمَلِ الثَّنَائِي',
    'tg.pairWorkModeDesc': 'يَقْرَأُ أَحَدُ الطُّلَّاب، وَيَدْعَمُ الآخَرُ بِالنِّقَاطِ السَّاخِنَةِ أَوِ التَّفْسِير.',
    'tg.quizMode': 'وَضْعُ الاخْتِبَار',
    'tg.quizModeDesc': 'اسْتَخْدِمِ الْفِرَقَ لِلتَّحْفِيز، وَلَيْسَ لِلضَّغْط.',
    'tg.exitTicketMode': 'وَضْعُ تَذْكِرَةِ الْخُرُوج',
    'tg.exitTicketModeDesc': 'اخْتِمْ كُلَّ دَرْسٍ بِتَحَقُّقٍ كِتَابِيٍّ قَصِير.',
    'tg.practicalNotes': 'مُلَاحَظَاتٌ عَمَلِيَّة',
    'tg.practicalNote1': 'حَافِظْ عَلَى سُرْعَةِ الانْتِقَالَات.',
    'tg.practicalNote2': 'لَا تَقْرَأْ كَثِيراً دُونَ تَوَقُّف.',
    'tg.practicalNote3': 'دَعِ الطُّلَّابَ الأَضْعَفَ يَتَدَرَّبُونَ فِي ثُنَائِيَّاتٍ قَبْلَ التَّحَدُّثِ أَمَامَ الْجَمِيع.',
    'tg.practicalNote4': 'اجْعَلِ اسْتِخْدَامَ النِّقَاطِ السَّاخِنَةِ هَادِفاً.',
    'tg.diffStrategies': 'اسْتِرَاتِيجِيَّاتُ التَّمَايُز',
    'tg.forSupport': 'لِلدَّعْم',
    'tg.forSupport1': 'اسْتَخْدِمِ الْمَرْئِيَّاتِ أَوَّلاً.',
    'tg.forSupport2': 'اطْرَحْ أَسْئِلَةَ نَعَمْ/لَا أَوْ هَذَا/ذَاك.',
    'tg.forSupport3': 'اسْمَحْ بِدَعْمٍ قَصِيرٍ بِاللُّغَةِ الأُمِّ لِلأَفْكَارِ الْمُجَرَّدَة.',
    'tg.forSupport4': 'كَرِّرِ الْجُمَلَ الرَّئِيسِيَّةَ مَعاً.',
    'tg.forSupport5': 'اسْتَخْدِمْ بِدَايَاتِ الْجُمَل.',
    'tg.forExtension': 'لِلتَّوَسُّع',
    'tg.forExtension1': 'اطْلُبْ تَدْوِينَاتِ الْيَوْمِيَّات.',
    'tg.forExtension2': 'اطْرَحْ أَسْئِلَةَ "لِمَاذَا" مَعَ إِطَارَاتِ الْجُمَل.',
    'tg.forExtension3': 'دَعِ الطُّلَّابَ يُصَمِّمُونَ مُلْصَقاً لِلْقِيَم.',
    'tg.forExtension4': 'اطْلُبْ مِنَ الطُّلَّابِ تَقْدِيمَ نَصِيحَةٍ بِاللُّغَةِ الإِنْجِلِيزِيَّة.',
    'tg.forMixedAbility': 'لِلْقُدُرَاتِ الْمُخْتَلِطَة',
    'tg.forMixedAbility1': 'اسْتَخْدِمْ دَعْمَ الأَقْرَان.',
    'tg.forMixedAbility2': 'أَعْطِ مَهَامَّ تَحَدٍّ اخْتِيَارِيَّة، وَلَيْسَ ضَغْطاً إِضَافِيّاً إِجْبَارِيّاً.',
    'tg.forMixedAbility3': 'حَافِظْ عَلَى بَسَاطَةِ النَّجَاحِ الأَسَاسِيِّ وَإِمْكَانِيَّةِ وُصُولِ الْجَمِيعِ إِلَيْه.',
    'tg.assessmentEvidence': 'أَدِلَّةُ التَّقْيِيمِ وَالتَّعَلُّم',
    'tg.lookFor': 'مَا الَّذِي يَجِبُ الْبَحْثُ عَنْه',
    'tg.lookFor1': 'هَلْ يَسْتَطِيعُ الطَّالِبُ مُتَابَعَةَ خَطِّ الْقِصَّةِ الرَّئِيسِي؟',
    'tg.lookFor2': 'هَلْ يَسْتَطِيعُ الطَّالِبُ اسْتِخْدَامَ بِضْعِ كَلِمَاتٍ مُسْتَهْدَفَةٍ بِشَكْلٍ صَحِيح؟',
    'tg.lookFor3': 'هَلْ يَسْتَطِيعُ الطَّالِبُ الإِجَابَةَ عَلَى أَسْئِلَةٍ بَسِيطَةٍ بِاللُّغَةِ الإِنْجِلِيزِيَّة؟',
    'tg.lookFor4': 'هَلْ يَسْتَطِيعُ الطَّالِبُ رَبْطَ الدَّرْسِ بِقِيمَةٍ أَوْ فِكْرَةٍ شَخْصِيَّة؟',
    'tg.masterRubric': 'مَصْفُوفَةُ التَّقْيِيمِ الرَّئِيسِيَّة (مُسْتَوَى A2)',
    'tg.criterion': 'الْمِعْيَار',
    'tg.excellent': 'مُمْتَاز (٥)',
    'tg.good': 'جَيِّد (٣)',
    'tg.developing': 'قَيْدُ التَّطْوِير (١)',
    'tg.kinestheticActivities': 'أَنْشِطَةُ التَّعَلُّمِ الْحَرَكِي',
    'tg.kinestheticDesc': 'اسْتَخْدِمِ الْحَرَكَةَ بِشَكْلٍ وَجِيزٍ وَهَادِف. يَجِبُ أَنْ تَدْعَمَ هَذِهِ الأَنْشِطَةُ اللُّغَةَ وَالتَّذَكُّر، لَا أَنْ تَحُلَّ مَحَلَّ الْقِرَاءَة.',
    'tg.statueGallery': 'مَعْرِضُ التَّمَاثِيل',
    'tg.vocabularyHop': 'قَفْزَةُ الْمُفْرَدَات',
    'tg.storyWalk': 'خَطُّ الْجَدْوَلِ الزَّمَنِيِّ لِلْقِصَّة',
    'tg.emotionMirroring': 'مُحَاكَاةُ الْعَوَاطِف',
    'tg.mimeAction': 'تَمْثِيلُ الْحَرَكَة',
    'tg.totalPhysicalResponse': 'الاسْتِجَابَةُ الْبَدَنِيَّةُ الْكَامِلَة (TPR)',
    'tg.totalPhysicalResponseDesc': 'اسْتَخْدِمِ الْحَرَكَةَ الْبَدَنِيَّةَ لِتَعْزِيزِ اللُّغَةِ وَالْمَفَاهِيم.',
    'tg.storyActing': 'تَمْثِيلُ الْقِصَّة',
    'tg.storyActingDesc': 'يُمَثِّلُ الطُّلَّابُ مَشَاهِدَ مِنَ الْقِصَّةِ لإِظْهَارِ الْفَهْم.',
    'tg.interactiveHotspots': 'النِّقَاطُ السَّاخِنَةُ التَّفَاعُلِيَّة',
    'tg.interactiveHotspotsDesc': 'اسْتَخْدِمِ النِّقَاطَ السَّاخِنَةَ الرَّقْمِيَّةَ لاسْتِكْشَافِ الْمُفْرَدَاتِ وَالْمَعَانِي الأَعْمَق.',
    'tg.classroomGames': 'أَلْعَابُ الْفَصْلِ الدِّرَاسِي',
    'tg.classroomGamesDesc': 'أَشْرِكِ الطُّلَّابَ فِي الأَلْعَابِ الَّتِي تُعِيدُ تَدْوِيرَ لُغَةِ الْقِصَّة.',
    'tg.storyWalkTimelineDesc': 'أَنْشِئْ جَدْوَلاً زَمَنِيّاً مَرْئِيّاً لِلأَحْدَاثِ فِي الْفَصْلِ الدِّرَاسِي.',
    'tg.globalCitizenship': 'الْمُوَاطَنَةُ الْعَالَمِيَّةُ وَجِسْرُ الْقِيَم',
    'tg.coreGlobalValues': 'الْقِيَمُ الْعَالَمِيَّةُ الأَسَاسِيَّة',
    'tg.keyThemes': 'الْمَوَاضِيعُ الرَّئِيسِيَّة',
    'tg.humanEquality': 'الْمُسَاوَاةُ الْبَشَرِيَّة',
    'tg.humanEqualityDesc': 'مُنَاقَشَةُ كَيْفَ أَنَّنَا جَمِيعاً مُرْتَبِطُونَ وَنَشْتَرِكُ فِي أَصْلٍ وَاحِد.',
    'tg.respectDifferences': 'الاحْتِرَامُ عَبْرَ الاخْتِلَافَات',
    'tg.respectDifferencesDesc': 'تَقْدِيرُ التَّنَوُّعِ فِي لَوْنِ الْبَشَرَةِ وَاللُّغَةِ وَالْخَلْفِيَّة.',
    'tg.natureResponsibility': 'الْمَسْؤُولِيَّةُ تُجَاهَ الطَّبِيعَة:',
    'tg.natureResponsibilityDesc': 'أَنْ نَكُونَ خُلَفَاءَ لِلأَرْض.',
    'tg.peacefulResolution': 'حَلُّ النِّزَاعَاتِ سِلْمِيّاً:',
    'tg.peacefulResolutionDesc': 'التَّعَلُّمُ مِنْ قِصَّةِ هَابِيلَ وَقَابِيل.',
    'tg.rejectingSuperiority': 'رَفْضُ الاسْتِعْلَاء:',
    'tg.rejectingSuperiorityDesc': 'فَهْمُ خَطَرِ الْكِبْر (إِبْلِيس).',
    'tg.actionPoints': 'نِقَاطُ الْعَمَل',
    'tg.globalAction1': 'إِذَا كَانَ كُلُّ النَّاسِ يَأْتُونَ مِنْ بِدَايَةٍ بَشَرِيَّةٍ وَاحِدَة، فَكَيْفَ يَجِبُ أَنْ نُعَامِلَ بَعْضَنَا الْبَعْض؟',
    'tg.globalAction2': 'لِمَاذَا مِنَ الْخَطَأِ الاعْتِقَادُ بِأَنَّ مَجْمُوعَةً وَاحِدَةً أَفْضَلُ مِنْ أُخْرَى؟',
    'tg.globalAction3': 'كَيْفَ يُمْكِنُنَا حَلُّ الْمَشَاكِلِ سِلْمِيّاً؟',
    'tg.suggestedQuestions': 'أَسْئِلَةٌ مُقْتَرَحَة',
    'tg.extraMaterials': 'مَوَارِدُ وَمَوَادُّ إِضَافِيَّة',
    'tg.printableWorksheets': 'مُسَوَّدَاتُ أَوْرَاقِ الْعَمَلِ الْقَابِلَةِ لِلطَّبْع',
    'tg.externalLinks': 'رَوَابِطُ خَارِجِيَّةٌ مُوصَى بِهَا',
    'tg.valuesCharacter': 'تَعْلِيمُ الْقِيَمِ وَالشَّخْصِيَّة',
    'tg.keyValues': 'الْقِيَمُ الأَسَاسِيَّة',
    'tg.humility': 'التَّوَاضُع',
    'tg.humilityQ': 'لِمَاذَا التَّوَاضُعُ أَفْضَلُ مِنَ الْكِبْر؟',
    'tg.sincerity': 'الإِخْلَاص',
    'tg.sincerityQ': 'لِمَاذَا الإِخْلَاصُ الْحَقِيقِيُّ مُهِم؟',
    'tg.responsibility': 'الْمَسْؤُولِيَّة',
    'tg.responsibilityQ': 'مَاذَا يَعْنِي الاهْتِمَامُ بِالْعَالَم؟',
    'tg.honesty': 'الصِّدْق',
    'tg.honestyQ': 'لِمَاذَا الصِّدْقُ مُهِم؟',
    'tg.regret': 'النَّدَم',
    'tg.regretQ': 'لِمَاذَا الاعْتِرَافُ بِالْخَطَأِ قُوَّة؟',
    'tg.peace': 'السَّلَامُ وَضَبْطُ النَّفْس',
    'tg.peaceQ': 'كَيْفَ يُمْكِنُنَا إِيقَافُ الْغَضَبِ قَبْلَ أَنْ يَنْمُو؟',
    'tg.jealousyQ': 'كَيْفَ يُمْكِنُنَا الثِّقَةُ بِاللهِ خِلالَ الاخْتِبَارَاتِ الصَّعْبَةِ؟',
    'tg.sensitiveGuidance': 'تَوْجِيهٌ بِيدَاغُوجِيٌّ حَسَّاس',
    'tg.keyGuidance': 'التَّوْجِيهُ الرَّئِيسِي',
    'tg.teacherTipsEnglish': 'نَصَائِحُ لِلْمُعَلِّمِ لاسْتِخْدَامِ الإِنْجِلِيزِيَّة',
    'tg.simpleClassroomEnglish': 'لُغَةٌ إِنْجِلِيزِيَّةٌ بَسِيطَةٌ لِلْفَصْل',
    'tg.supportMeaning': 'دَعْمُ الْمَعْنَى',
    'tg.praiseEffort': 'الثَّنَاءُ عَلَى الْجُهْد',
    'tg.consistency': 'الاتِّسَاق',
    'tg.recycle': 'إِعَادَةُ التَّدْوِير',
    'tg.l1Use': 'اسْتِخْدَامُ اللُّغَةِ الأُم',
    'tg.production': 'الإِنْتَاج',
    'tg.usefulLanguage': 'لُغَةٌ مُفِيدَةٌ لِلْفَصْلِ الدِّرَاسِي',
    'tg.familyPrompt': 'مُوَجِّهُ نِقَاشٍ عَائِلِي',
    'tg.sampleHomeTasks': 'مَهَامُّ مَنْزِلِيَّةٌ عَيِّنَة',
    'tg.quickChecklist': 'قَائِمَةٌ مَرْجِعِيَّةٌ سَرِيعَةٌ لِلاسْتِخْدَام',
    'tg.beforeClass': 'قَبْلَ الْفَصْل',
    'tg.duringClass': 'أَثْنَاءَ الْفَصْل',
    'tg.afterClass': 'بَعْدَ الْفَصْل',
    'tg.readyAppendices': 'مَلَاحِقُ جَاهِزَةٌ لِلاسْتِخْدَام',
    'tg.sampleExitTicket': 'عَيِّنَةُ تَذْكِرَةِ خُرُوج',
    'tg.preTeach': 'قُمْ بِتَدْرِيسِ عَدَدٍ قَلِيلٍ فَقَطْ مِنَ الْكَلِمَاتِ الرَّئِيسِيَّةِ مُسْبَقاً. اسْتَخْدِمِ الْمَرْئِيَّاتِ أَوَّلاً، ثُمَّ الصَّوْت، ثُمَّ النَّص. انْتَقِلْ مِنْ "مَاذَا حَدَث؟" إِلَى "لِمَاذَا حَدَث؟"',
    'tg.sequence': '١. رُؤْيَتُهُ (مَرْئِيَّات). ٢. سَمَاعُهُ (صَوْت). ٣. قِرَاءَتُهُ (نَص). ٤. قَوْلُهُ (إِجَابَة/إِعَادَةُ سَرْد). ٥. رَبْطُهُ (رَبْطٌ بِالْحَيَاة).',
    'tg.guideNotLecturer': 'كُنْ مُرْشِداً، وَلَيْسَ مُحَاضِراً. سَاعِدِ الطُّلَّابَ عَلَى الْمُلَاحَظَةِ وَالْفَهْمِ وَالتَّحَدُّثِ وَالتَّأَمُّل.',
    'tg.pairTalk': 'اسْتَخْدِمِ الْمُحَادَثَةَ الثَّنَائِيَّةَ قَبْلَ إِجَابَاتِ الْفَصْلِ بِأَكْمَلِه. اخْتِمْ كُلَّ دَرْسٍ بِجِسْرٍ قَصِيرٍ لِلْحَيَاةِ الْوَاقِعِيَّة.',
    'tg.clearTeacherTalk': 'اجْعَلْ حَدِيثَ الْمُعَلِّمِ وَاضِحاً وَقَصِيراً. كَرِّرِ اللُّغَةَ الْمُهِمَّةَ بِطُرُقٍ طَبِيعِيَّة.',
    'ssg.whoIsThisFor': '١. لِمَنْ هَذَا؟',
    'ssg.whoIsThisForDesc': 'هَذَا الدَّلِيلُ مُخَصَّصٌ لِمُتَعَلِّمِي اللُّغَةِ الإِنْجِلِيزِيَّةِ بِمُسْتَوَى A2 (الصُّفُوف ٦-٨). يُسَاعِدُكَ عَلَى فَهْمِ الْقِصَّةِ وَتَعَلُّمِ كَلِمَاتٍ جَدِيدَةٍ بِسُهُولَة.',
    'ssg.learnerType1': 'طُلَّابُ اللُّغَةِ الإِنْجِلِيزِيَّة',
    'ssg.learnerType2': 'الْمُتَعَلِّمُونَ الَّذِينَ يَدْرُسُونَ بِمُفْرَدِهِمْ أَوْ مَعَ مُعَلِّم',
    'ssg.whatInBook': '٢. مَاذَا يُوجَدُ فِي الْكِتَاب؟',
    'ssg.whatInBookDesc': 'هَذَا كِتَابُ قِصَصٍ تَفَاعُلِيٌّ عَنِ النَّبِيِّ آدَم. يَحْتَوِي عَلَى أَكْثَرَ مِنْ مُجَرَّدِ نَص!',
    'ssg.content1': 'قِصَصٌ لِلْقِرَاءَةِ وَالاسْتِمَاع',
    'ssg.content2': 'صُوَرٌ وَمُسَاعَدَةٌ فِي الْكَلِمَات',
    'ssg.content3': 'أَلْعَابٌ وَاخْتِبَارَات',
    'ssg.content4': 'أَسْئِلَةٌ لِلتَّفْكِير',
    'ssg.howToUse': '٣. كَيْفَ تَسْتَخْدِمُ الْكِتَاب',
    'ssg.howToUseDesc': 'اتَّبِعْ هَذِهِ الْخُطُوَاتِ الأَرْبَعَ الْبَسِيطَةَ لِكُلِّ صَفْحَة:',
    'ssg.step1': 'الْخُطْوَة ١: انْظُرْ إِلَى الصُّورَةِ وَالْعُنْوَان.',
    'ssg.step2': 'الْخُطْوَة ٢: اسْتَمِعْ إِلَى الصَّوْتِ أَوَّلاً.',
    'ssg.step3': 'الْخُطْوَة ٣: اقْرَأِ النَّصَّ بِبُطْء.',
    'ssg.step4': 'الْخُطْوَة ٤: قُمْ بِالأَنْشِطَةِ وَتَحَقَّقْ مِنَ الْمُلَاحَظَات.',
    'ssg.routine': '٤. رُوتِينُ دِرَاسَتِك',
    'ssg.routineDesc': 'لَا تَحْتَاجُ إِلَى سَاعَات. الْخُطُوَاتُ الصَّغِيرَةُ أَفْضَل!',
    'ssg.routine1': 'قَصِير (١٠ دَقَائِق): اسْتَمِعْ وَاقْرَأْ وَقُمْ بِنَشَاطٍ وَاحِد.',
    'ssg.routine2': 'عَادِي (٢٠ دَقِيقَة): اسْتَمِعْ وَاقْرَأْ وَتَعَلَّمْ ٥ كَلِمَاتٍ وَقُمْ بِجَمِيعِ الأَنْشِطَة.',
    'ssg.routine3': 'طَوِيل (٤٠ دَقِيقَة): دِرَاسَةٌ كَامِلَةٌ وَاكْتُبْ مُلَخَّصاً وَرَاجِعِ الْكَلِمَاتِ الْقَدِيمَة.',
    'ssg.readingTips': '٥. نَصَائِحُ لِلْقِرَاءَة',
    'ssg.readingTipsDesc': 'كَيْفَ تَقْرَأُ مِثْلَ الْمُحْتَرِفِين:',
    'ssg.readingTip1': 'قَبْل: انْظُرْ إِلَى الصُّورَةِ وَخَمِّنِ الْقِصَّة.',
    'ssg.readingTip2': 'أَثْنَاء: اقْرَأْ أَجْزَاءً صَغِيرَة. لَا تَسْتَعْجِلْ!',
    'ssg.readingTip3': 'بَعْد: قُلْ جُمْلَةً وَاحِدَةً عَمَّا حَدَث.',
    'ssg.learningWords': '٦. تَعَلُّمُ كَلِمَاتٍ جَدِيدَة',
    'ssg.learningWordsDesc': 'لَا تُحَاوِلْ تَعَلُّمَ كُلِّ شَيْء. اخْتَرْ ٣-٥ كَلِمَاتٍ فِي كُلِّ صَفْحَة.',
    'ssg.learningWord1': 'لَاحِظ: ابْحَثْ عَنْ كَلِمَةٍ جَدِيدَة.',
    'ssg.learningWord2': 'افْهَم: انْقُرْ عَلَيْهَا لِرُؤْيَةِ الْمَعْنَى.',
    'ssg.learningWord3': 'اكْتُب: ضَعْهَا فِي دَفْتَرِ مُلَاحَظَاتِكَ مَعَ مِثَال.',
    'ssg.learningWord4': 'رَاجِع: انْظُرْ إِلَيْهَا مَرَّةً أُخْرَى غَداً.',
    'ssg.listeningSpeaking': '٧. الاسْتِمَاعُ وَالتَّحَدُّث',
    'ssg.listeningSpeakingDesc': 'اسْتَخْدِمْ أُذُنَيْكَ وَصَوْتَك!',
    'ssg.listeningSpeaking1': 'اسْتَمِعْ ٣ مَرَّات: فِكْرَةٌ عَامَّة -> مَعَ النَّص -> كَرِّرِ الْجُمَل.',
    'ssg.listeningSpeaking2': 'تَحَدَّثْ بِصَوْتٍ عَالٍ: اقْرَأِ الْجُمَلَ بَعْدَ الصَّوْتِ لِمُمَارَسَةِ النُّطْق.',
    'ssg.writingPractice': '٨. مُمَارَسَةُ الْكِتَابَة',
    'ssg.writingPracticeDesc': 'الْكِتَابَةُ تُسَاعِدُكَ عَلَى التَّذَكُّر.',
    'ssg.writingPractice1': 'اكْتُبْ ٣ كَلِمَاتٍ جَدِيدَة.',
    'ssg.writingPractice2': 'اكْتُبْ دَرْساً وَاحِداً تَعَلَّمْتَه.',
    'ssg.writingPractice3': 'اكْتُبْ مُلَخَّصاً قَصِيراً جِدّاً (جُمْلَتَان).',
    'ssg.whenHard': '٩. عِنْدَمَا تَشْعُرُ بِالصُّعُوبَة',
    'ssg.whenHardDesc': 'لَا بَأْسَ فِي ارْتِكَابِ الأَخْطَاء! هَكَذَا نَتَعَلَّم.',
    'ssg.whenHard1': 'خُذِ اسْتِرَاحَةً قَصِيرَة.',
    'ssg.whenHard2': 'اسْتَمِعْ مَرَّةً أُخْرَى. سَيُصْبِحُ الأَمْرُ أَسْهَل!',
    'ssg.whenHard3': 'اطْلُبِ الْمُسَاعَدَةَ مِنْ مُعَلِّمٍ أَوْ صَدِيق.',
    'ssg.chapterSupport': '١٠. دَعْمُ الْفُصُول',
    'ssg.chapterSupportDesc': 'نَصَائِحُ سَرِيعَةٌ لِرِحْلَتِك:',
    'ssg.chapterSupport1': 'الْفُصُول الأولى: التَّرْكِيزُ عَلَى التَّوْحِيدِ، وَالْبَحْثِ عَنِ الْحَقِيقَةِ، وَرَفْضِ الأَصْنَامِ.',
    'ssg.chapterSupport2': 'الْفُصُول الوسطى: التَّرْكِيزُ عَلَى الشَّجَاعَةِ، وَالْمُنَاظَرَةِ، وَالتَّوَكُّلِ عَلَى اللهِ، وَالابْتِلاءَاتِ.',
    'ssg.chapterSupport3': 'الْفُصُول الأخيرة: التَّرْكِيزُ عَلَى الأسْرَةِ، وَالتَّضْحِيَةِ، وَمَوْضُوعَاتِ زَمْزَمَ وَالْكَعْبَةِ.',
    'ssg.welcome': 'مَرْحَباً',
    'ex.perfect': 'مُمْتَاز!',
    'ex.amazing': 'مُذْهِل!',
    'ex.goodJob': 'عَمَلٌ جَيِّد!',
    'ex.keepGoing': 'اسْتَمِر!',
    'ex.streak': 'مُتَتَالِي!',
    'ex.pts': 'نِقَاط',
    'ex.true': 'صَحِيح',
    'ex.false': 'خَطَأ',
    'ex.tfChallenge': 'تَحَدِّي صَح / خَطَأ',
    'ex.seeResults': 'رُؤْيَةُ النَّتَائِج',
    'ex.tryAgain': 'حَاوِلْ مَرَّةً أُخْرَى',
    'ex.correct': 'صَحِيح!',
    'ex.notQuite': 'لَيْسَ تَمَاماً!',
    'ex.explanation': 'التَّفْسِير',
    'ex.scoreSummary': 'لَقَدْ أَجَبْتَ عَلَى {correct} مِنْ أَصْلِ {total} بِشَكْلٍ صَحِيح ({percent}%).',
    'ex.feedbackPanel': 'لَوْحَةُ الْمُلَاحَظَات',
    'ex.feedbackHint': 'أَجِبْ عَلَى جَمِيعِ الأَسْئِلَة، ثُمَّ انْقُرْ عَلَى أَيْقُونَةِ {info} لِرُؤْيَةِ مُلَاحَظَاتٍ مُفَصَّلَة.',
    'ex.perfectOrder': 'تَرْتِيبٌ مِثَالِي!',
    'ex.allEventsCorrect': 'جَمِيعُ الأَحْدَاثِ الـ {total} فِي التَّسَلْسُلِ الصَّحِيح.',
    'ex.firstTry': 'مِنَ الْمُحَاوَلَةِ الأُولَى — مُمْتَاز!',
    'ex.secondTry': 'نَجَحْتَ فِي الْمُحَاوَلَةِ الثَّانِيَة!',
    'ex.completedIn': 'تَمَّ الإِكْمَالُ فِي {attempts} مُحَاوَلَات.',
    'ex.itemsOutOfPlace': '{count} عَنَاصِرَ فِي غَيْرِ مَكَانِهَا',
    'ex.itemOutOfPlace': 'عُنْصُرٌ وَاحِدٌ فِي غَيْرِ مَكَانِه',
    'ex.rearrangeHint': 'الْعَنَاصِرُ الْمُمَيَّزَةُ بِـ ✗ تُظْهِرُ مَوْقِعَهَا الصَّحِيح. أَعِدِ التَّرْتِيبَ وَحَاوِلْ مَرَّةً أُخْرَى!',
    'ex.showAnswer': 'إِظْهَارُ الإِجَابَة',
    'ex.retry': 'إِعَادَةُ الْمُحَاوَلَة',
    'ex.dragHint': 'اسْحَبِ الْعَنَاصِرَ بِاسْتِخْدَامِ ≡ لِتَرْتِيبِهَا بِالتَّسَلْسُلِ الصَّحِيح، ثُمَّ انْقُرْ عَلَى تَحَقُّق.',
    'ex.sequenceChallenge': 'تَحَدِّي التَّسَلْسُل',
    'ex.arrangeOrder': 'رَتِّبِ الأَحْدَاثَ بِالتَّسَلْسُلِ الصَّحِيح',
    'ex.attempt': 'مُحَاوَلَة',
    'ex.verifySequence': 'تَحَقَّقْ مِنَ التَّسَلْسُل',
    'ex.allWordsMatched': 'تَمَّتْ مُطَابَقَةُ جَمِيعِ الْكَلِمَاتِ الـ {total}!',
    'ex.bestStreak': 'أَفْضَلُ سِلْسِلَة: {count} مُتَتَالِيَة — تَرْكِيزٌ مُمْتَاز!',
    'ex.greatWork': 'عَمَلٌ رَائِعٌ فِي إِكْمَالِ التَّمْرِين!',
    'ex.means': 'تَعْنِي',
    'ex.doesNotMean': 'لَا تَعْنِي',
    'ex.keepTrying': 'اسْتَمِرْ فِي الْمُحَاوَلَة!',
    'ex.selectWordHint': 'اخْتَرْ كَلِمَة، ثُمَّ اخْتَرْ مَعْنَاهَا لإِجْرَاءِ مُطَابَقَة.',
    'ex.allMatchedJob': 'تَمَّتْ مُطَابَقَةُ جَمِيعِ الْكَلِمَاتِ — عَمَلٌ رَائِع!',
    'ex.tapToBegin': 'انْقُرْ عَلَى كَلِمَةٍ أَوْ مَعْنًى لِلْبَدْء',
    'ex.wordSelectedHint': 'تَمَّ اخْتِيَارُ "{word}" — الآنَ اخْتَرْ مَعْنَاهَا',
    'ex.meaningSelectedHint': 'تَمَّ اخْتِيَارُ الْمَعْنَى — الآنَ اخْتَرْ الْكَلِمَةَ الْمُطَابِقَة',
    'ex.words': 'الْكَلِمَات',
    'ex.meanings': 'الْمَعَانِي',
    'ex.type.true-false': 'صَحٌّ أَمْ خَطَأ',
    'ex.type.multiple-choice': 'اخْتِيَارٌ مِنْ مُتَعَدِّد',
    'ex.type.sequencing': 'تَرْتِيبُ الأَحْدَاث',
    'ex.type.vocabulary-match': 'مُطَابَقَةُ الْمُفْرَدَات',
    'ex.type.quiz': 'اخْتِبَار',
    'ex.type.quiz-game': 'لُعْبَةُ اخْتِبَار',
    'ex.type.game': 'لُعْبَة',
    'ex.type.exercises': 'تَمَارِين',
    'ex.type.drag-drop': 'سَحْبٌ وَإِفْلَات',
    'ex.type.reflection': 'تَأَمُّل',
    'ex.type.tap-reveal': 'انْقُرْ لِلْكَشْف',
    'nav.keyWordFallback': 'كَلِمَةٌ رَئِيسِيَّةٌ فِي هَذِهِ الْقِصَّة.',
    'tg.exitTicket1': 'شَيْءٌ وَاحِدٌ تَعَلَّمْتُهُ الْيَوْم: ________',
    'tg.exitTicket2': 'كَلِمَةٌ وَاحِدَةٌ أُرِيدُ تَذَكُّرَهَا: ______',
    'tg.exitTicket3': 'سُؤَالٌ وَاحِدٌ لَا يَزَالُ لَدَيّ: ________',
    'tg.miniProjectIdea': 'فِكْرَةُ مَشْرُوعٍ صَغِير',
    'tg.miniProjectDesc': '"أَنْشِئْ قِصَّةً مُصَوَّرَةً مِنْ ٣ لَوْحَاتٍ تُظْهِرُ خِيَاراً جَيِّداً، وَخَطَأً، وَاسْتِجَابَةً أَفْضَل. أَضِفْ تَعْلِيقَاتٍ قَصِيرَةً بِاللُّغَةِ الإِنْجِلِيزِيَّة."',
    'tg.reflectiveWritingPrompt': 'مُوَجِّهُ الْكِتَابَةِ التَّأَمُّلِيَّة',
    'tg.reflectiveWritingDesc': '“يَرْتَكِبُ النَّاسُ أَخْطَاءً، لَكِنْ يُمْكِنُهُمُ التَّعَلُّمُ وَالْعَوْدَةُ إِلَى الطَّرِيقِ الصَّحِيح. اكْتُبْ عَنْ وَقْتٍ تَعَلَّمْتَ فِيهِ مِنْ خَطَأ.”',
    'tg.storyWalkTimeline': 'خَطُّ الْجَدْوَلِ الزَّمَنِيِّ لِلْقِصَّة',
    'tg.creationMap': 'خَرِيطَةُ الْخَلْق',
    'tg.creationMapType': 'تَسَلْسُلٌ وَرَسْم',
    'tg.characterTraitsChart': 'مُخَطَّطُ سِمَاتِ الشَّخْصِيَّة',
    'tg.characterTraitsChartType': 'صِفَاتٌ وَأَدِلَّة',
    'tg.regretLetter': 'رِسَالَةُ النَّدَم',
    'tg.regretLetterType': 'مُوَجِّهُ كِتَابَةٍ إِبْدَاعِيَّة',
    'tg.vocabularyCrossword': 'كَلِمَاتٌ مُتَقَاطِعَةٌ لِلْمُفْرَدَات',
    'tg.vocabularyCrosswordType': 'مُرَاجَعَةُ الْفُصُول ١-٥',
    'tg.interactiveWordList': 'قَائِمَةُ كَلِمَاتِ CEFR A2 التَّفَاعُلِيَّة',
    'tg.guidance1': 'قَدِّمْ خَطَأَ آدَمَ كَلَحْظَةِ تَعَلُّم.',
    'tg.guidance2': 'تَعَامَلْ مَعَ وَفَاةِ هَابِيلَ بِهُدُوءٍ وَعِنَايَة.',
    'tg.guidance3': 'قَدِّمْ إِبْلِيسَ كَمِثَالٍ تَحْذِيرِيٍّ لِلْكِبْر.',
    'tg.guidance4': 'حَافِظْ عَلَى لُغَةٍ مُنَاسِبَةٍ لِلْعُمْرِ وَغَيْرِ مُصَوَّرَة.',
    'tg.guidance5': 'رَكِّزْ عَلَى الدَّرْسِ وَالنَّتِيجَةِ وَالْخِيَارَاتِ الأَفْضَل.',
    'tg.simpleEnglishDesc': 'حَافِظْ عَلَى لُغَةِ الْفَصْلِ الإِنْجِلِيزِيَّةِ بَسِيطَةً وَقَابِلَةً لِلتَّكْرَار.',
    'tg.supportMeaningDesc': 'ادْعَمِ الْمَعْنَى بِالْمَرْئِيَّاتِ وَالإِيمَاءَاتِ وَالتَّكْرَارِ وَإِطَارَاتِ الْجُمَل.',
    'tg.praiseEffortDesc': 'أَثْنِ عَلَى الْجُهْدِ بِشَكْلٍ مُحَدَّد.',
    'tg.consistencyDesc': 'اجْعَلِ التَّعْلِيمَاتِ قَصِيرَةً وَمُتَّسِقَة.',
    'tg.recycleDesc': 'أَعِدْ تَدْوِيرَ الْكَلِمَاتِ الْمُسْتَهْدَفَةِ عَبْرَ الدُّرُوس.',
    'tg.l1UseDesc': 'اسْتَخْدِمِ اللُّغَةَ الْعَرَبِيَّةَ فَقَطْ لِفَتْرَةٍ وَجِيزَةٍ عِنْدَ الْحَاجَةِ الْحَقِيقِيَّةِ لِلْمَعْنَى الْمُجَرَّد.',
    'tg.productionDesc': 'أَعِدْ إِنْتَاجَ الطُّلَّابِ إِلَى اللُّغَةِ الإِنْجِلِيزِيَّةِ كُلَّمَا أَمْكَنَ ذَلِكَ.',
    'tg.classroomLang1': '“اسْتَمِعْ وَتَابِعْ.”',
    'tg.classroomLang2': '“اعْمَلْ مَعَ شَرِيكِك.”',
    'tg.classroomLang3': '“قُلْ جُمْلَةً وَاحِدَة.”',
    'tg.classroomLang4': '“مَاذَا حَدَثَ أَوَّلاً؟”',
    'tg.classroomLang5': '“لِمَاذَا تَعْتَقِدُ ذَلِكَ؟”',
    'tg.classroomLang6': '“اسْتَخْدِمِ الْكَلِمَةَ الْجَدِيدَةَ فِي إِجَابَتِك.”',
    'tg.homeAction1': 'اطْلُبْ مِنَ الطُّلَّابِ مُنَاقَشَةَ دَرْسٍ وَاحِدٍ مَعَ الْعَائِلَة.',
    'tg.homeAction2': 'شَجِّعْ مُمَارَسَةَ الاسْتِمَاعِ فِي الْمَنْزِل.',
    'tg.homeAction3': 'أَعْطِ مَهَامَّ تَأَمُّلٍ قَصِيرَةً لَا تَخْلُقُ وَاجِباً مَنْزِلِيّاً ثَقِيلاً.',
    'tg.homeAction4': 'اسْتَخْدِمِ الْوَاجِبَ الْمَنْزِلِيَّ لإِعَادَةِ تَدْوِيرِ اللُّغَة، وَلَيْسَ لإِرْهَاقِ الْمُتَعَلِّمِين.',
    'tg.informativeNarratives': '"النُّصُوصُ الْوَارِدَةُ هُنَا هِيَ رِوَايَاتٌ إِخْبَارِيَّة."',
    'tg.parentTask1': 'اسْتَمِعْ مَرَّةً أُخْرَى وَكَرِّرْ ٥ أَسْطُر.',
    'tg.parentTask2': 'اطْرَحْ سُؤَالاً وَاحِداً لِلنِّقَاشِ الْعَائِلِي.',
    'tg.parentTask3': 'اكْتُبْ ٢-٣ جُمَلٍ بَسِيطَةً بِاسْتِخْدَامِ الْمُفْرَدَاتِ الْجَدِيدَة.',
    'tg.checklistBefore1': 'تَحَقَّقْ مِنَ الشَّاشَةِ وَالصَّوْت.',
    'tg.checklistBefore2': 'افْتَحِ الصَّفْحَةَ الصَّحِيحَة.',
    'tg.checklistBefore3': 'جَهِّزْ ٤-٦ كَلِمَاتٍ مُسْتَهْدَفَة.',
    'tg.checklistBefore4': 'قَرِّرْ أَيْنَ سَتَتَوَقَّف.',
    'tg.checklistDuring1': 'حَافِظْ عَلَى وَتِيرَةٍ يُمْكِنُ التَّحَكُّمُ فِيهَا.',
    'tg.checklistDuring2': 'تَوَقَّفْ بَعْدَ مَقَاطِعَ قَصِيرَة.',
    'tg.checklistDuring3': 'اسْتَخْدِمِ الْمُحَادَثَةَ الثَّنَائِيَّةَ قَبْلَ الرُّدُود.',
    'tg.checklistDuring4': 'تَحَقَّقْ مِنَ الْفَهْمِ غَالِباً.',
    'tg.checklistAfter1': 'اجْمَعْ تَذَاكِرَ الْخُرُوج.',
    'tg.checklistAfter2': 'لَاحِظِ الْمُفْرَدَاتِ الصَّعْبَة.',
    'tg.checklistAfter3': 'سَجِّلِ احْتِيَاجَاتِ الْمُرَاجَعَة.',
    'tg.checklistAfter4': 'اضْبِطِ الدَّرْسَ التَّالِي.',
    'tg.sentence1': '“خُلِقَ آدَمُ مِنْ ...”',
    'tg.sentence2': '“الْعِلْمُ مُهِمٌّ لِأَنَّ ...”',
    'tg.sentence3': '“كَانَ آدَمُ أَكْثَرَ ... مِنْ ...”',
    'tg.sentence4': '“أَوَّلاً ... ثُمَّ ... بَعْدَ ذَلِكَ ...”',
    'tg.sentence5': '“دَرْسُ هَذِهِ الْقِصَّةِ هُوَ ...”',
    'ssg.sectionOf': 'الْقِسْمُ {section} مِنْ {total} • دَلِيلُ الدِّرَاسَةِ الذَّاتِيَّةِ لِلطَّالِب',
    'ssg.welcomeExplorer': 'أَهْلاً بِكَ أَيُّهَا الْمُسْتَكْشِف!',
    'ssg.welcomeDesc': 'هَذَا الْكِتَابُ هُوَ رِحْلَتُكَ عَبْرَ التَّارِيخِ وَالْحِكْمَة. أَنْتَ لَا تَقْرَأُ فَقَط؛ بَلْ تَتَعَلَّمُ كَيْفَ تَكُونُ شَخْصاً أَفْضَلَ مِنْ خِلَالِ قِصَّةِ أَوَّلِ إِنْسَان.',
    'ssg.yourMission': 'مُهِمَّتُك',
    'ssg.missionDesc': '"اقْرَأْ بِعِنَايَة، وَاسْتَمِعْ بِتَرْكِيز، وَفَكِّرْ بِعُمْق. كُلُّ صَفْحَةٍ لَهَا دَرْسٌ لِقَلْبِكَ وَعَقْلِك."',
    'ssg.fullGuide': 'الدَّلِيلُ الْكَامِل',
    'bg.rollToStart': 'ارْمِ النَّرْدَ لِبَدْءِ رِحْلَتِك!',
    'bg.journeyComplete': 'اكْتَمَلَتِ الرِّحْلَة',
    'bg.rollDice': 'ارْمِ النَّرْد',
    'bg.cell.1.title': 'الْبِدَايَة',
    'bg.cell.1.info': 'تَبْدَأُ الرِّحْلَة.',
    'bg.cell.2.title': 'الطِّين',
    'bg.cell.2.info': 'خُلِقَ الإِنْسَانُ مِنْ طِينٍ مُتَوَاضِع.',
    'bg.cell.3.title': 'الأَسْمَاء',
    'bg.cell.3.info': 'الْعِلْمُ هِبَةٌ مِنَ الله.',
    'bg.cell.4.title': 'الْمَلَائِكَة',
    'bg.cell.4.info': 'سَجَدُوا طَاعَةً لِلَّه.',
    'bg.cell.5.title': 'إِبْلِيس',
    'bg.cell.5.info': 'الْكِبْرِيَاءُ يُؤَدِّي إِلَى السُّقُوط.',
    'bg.cell.6.title': 'الْجَنَّة',
    'bg.cell.6.info': 'مَكَانٌ لِلسَّلَامِ وَالْجَمَال.',
    'bg.cell.7.title': 'الاخْتِبَار',
    'bg.cell.7.info': 'كُلُّ نِعْمَةٍ تَأْتِي مَعَ اخْتِبَار.',
    'bg.cell.8.title': 'الشَّجَرَة',
    'bg.cell.8.info': 'الْحُدُودُ هِيَ لِحِمَايَتِنَا.',
    'bg.cell.9.title': 'الْوَسْوَسَة',
    'bg.cell.9.info': 'احْذَرْ مِنْ خِدَاعِ الشَّيْطَان.',
    'bg.cell.10.title': 'الْخَطَأ',
    'bg.cell.10.info': 'الْبَشَرُ عُرْضَةٌ لِلْخَطَأ.',
    'bg.cell.11.title': 'التَّوْبَة',
    'bg.cell.11.info': 'اللهُ هُوَ الْغَفُورُ الرَّحِيم.',
    'bg.cell.12.title': 'الأَرْض',
    'bg.cell.12.info': 'بِدَايَةٌ جَدِيدَةٌ كَخُلَفَاء.',
  }
};

const arabicNumerals = ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'];

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const formatNumber = (num: number | string) => {
    if (language !== 'ar') return String(num);
    return String(num).replace(/[0-9]/g, (d) => arabicNumerals[parseInt(d)]);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRTL, t, formatNumber }}>
      <div className={isRTL ? 'font-arabic' : 'font-sans'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
